import json

data = json.load(open(r'h:\Github\PrincipiaMetaphysica\AutoGenerated\theory_output.json', encoding='utf-8'))
params_with_exp = [(k, v) for k, v in data['parameters'].items() if 'experimentalValue' in v]

print(f'Total parameters with experimental values: {len(params_with_exp)}')
print('\nSample parameters:')
for k, v in params_with_exp[:5]:
    print(f'\n{k}:')
    print(f'  Computed: {v["value"]} +/- {v.get("uncertainty", 0)}')
    print(f'  Experimental: {v["experimentalValue"]} +/- {v["experimentalUncertainty"]}')
    print(f'  Source: {v["experimentalSource"]}')
    if 'sigmaDeviation' in v:
        print(f'  Deviation: {v["sigmaDeviation"]:.2f} sigma')
