#!/usr/bin/env python3
"""Copy certificate files to zenodo_package"""
import shutil
import os
from pathlib import Path

# Base paths
base = Path(r"H:\Github\PrincipiaMetaphysica")
cert_dir = base / "zenodo_package" / "certificates"
wolfram_dir = cert_dir / "wolfram_proofs"

# Create directories
cert_dir.mkdir(parents=True, exist_ok=True)
wolfram_dir.mkdir(parents=True, exist_ok=True)

# Copy main files
files_to_copy = [
    ("AutoGenerated/discovery_hashes.json", "discovery_hashes.json"),
    ("AutoGenerated/formal_proof_manifest.json", "wolfram_formal_proof_manifest.json"),
    ("AutoGenerated/web_proofs.json", "wolfram_web_proofs.json"),
    ("IP_HEADERS_AUDIT.md", "IP_HEADERS_AUDIT.md"),
    ("DISCOVERY_PRIORITY.md", "DISCOVERY_PRIORITY.md"),
]

print("Copying main certificate files...")
for src, dst in files_to_copy:
    src_path = base / src
    dst_path = cert_dir / dst
    if src_path.exists():
        shutil.copy2(src_path, dst_path)
        print(f"  [OK] {dst}")
    else:
        print(f"  [MISS] Missing: {src}")

# Copy individual Wolfram proofs
wolfram_src = base / "AutoGenerated" / "certificates"
if wolfram_src.exists():
    print(f"\nCopying Wolfram proof certificates...")
    count = 0
    for json_file in wolfram_src.glob("*.json"):
        shutil.copy2(json_file, wolfram_dir / json_file.name)
        count += 1
    print(f"  [OK] Copied {count} proof certificates")

# List final contents
print(f"\nFinal package contents:")
print(f"  Main files: {len(list(cert_dir.glob('*.json'))) + len(list(cert_dir.glob('*.md')))}")
print(f"  Wolfram proofs: {len(list(wolfram_dir.glob('*.json')))}")

print("\nCertificates package ready!")
