#!/usr/bin/env python3
"""
Create Zenodo website export package.
Copies all essential website files and generates a manifest with checksums.
"""

import os
import json
import shutil
import hashlib
from pathlib import Path
from datetime import datetime

# Base paths
BASE_DIR = Path(__file__).parent
ZENODO_WEBSITE_DIR = BASE_DIR / "zenodo_package" / "website"

# File collections to copy
FILES_TO_COPY = {
    "root": ["index.html"],
    "Pages": [
        "paper.html",
        "sections.html",
        "formulas.html",
        "parameters.html",
        "beginners-guide.html",
        "foundations.html",
        "appendices.html",
        "references.html",
        "simulations.html",
        "visualization-index.html",
        "philosophical-implications.html"
    ],
    "js": [
        # Core rendering
        "pm-paper-renderer.js",
        "pm-section-renderer.js",
        "pm-section-loader.js",
        "pm-formula-renderer.js",
        "pm-formula-loader.js",
        "pm-parameter-component.js",
        "pm-parameter-table.js",
        "pm-beginner-guide-loader.js",
        "pm-foundations-loader.js",

        # Components
        "pm-formula-component.js",
        "pm-header.js",
        "pm-tooltip-system.js",
        "pm-paper-tooltips.js",
        "pm-paper-param-processor.js",
        "pm-paper-tooltips-integration.js",
        "pm-paper-renderer-blocks-patch.js",
        "pm-citations.js",

        # Data loaders
        "pm-parameter-schema.js",
        "pm-parameter-data.js",
        "pm-constants-loader.js",
        "pm-template-engine.js",

        # Theory/validation
        "theory-constants.js",
        "theory-constants-enhanced.js",
        "theory-computations.js",
        "theory-derivations.js",
        "pm-validation-stats.js",
        "validation-stats.js",
        "simulation-stats.js",

        # Formulas
        "formula-registry.js",
        "formula-database.js",
        "formula-definitions.js",
        "formula-expansion.js",

        # Content
        "content-templates.js",

        # Utilities
        "pm-param-paper.js",
        "pm-foundation-page.js"
    ],
    "css": [
        "styles.css",
        "pm-common.css",
        "pm-glass-theme.css",
        "pm-scientific-typography.css",
        "pm-section-paper.css",
        "pm-tooltip.css",
        "pm-paper-tooltips.css",
        "pm-header.css",
        "pm-citations.css",
        "formula-metadata.css",
        "formula-display-fix.css",
        "formula-hover.css",
        "mobile-responsive.css",
        "styles-mobile-enhanced.css",
        "desktop-optimizations.css"
    ],
    "AutoGenerated": [
        "theory_output.json",
        "formulas.json",
        "parameters.json",
        "sections.json",
        "metadata.json",
        "beginner-guide.json",
        "index.json",
        "statistics.json"
    ]
}


def calculate_sha256(file_path):
    """Calculate SHA-256 checksum of a file."""
    sha256_hash = hashlib.sha256()
    with open(file_path, "rb") as f:
        for byte_block in iter(lambda: f.read(4096), b""):
            sha256_hash.update(byte_block)
    return sha256_hash.hexdigest()


def get_file_description(category, filename):
    """Generate a description for each file."""
    descriptions = {
        "index.html": "Main landing page for Principia Metaphysica website",

        # Pages
        "paper.html": "Full academic paper view with dynamic rendering",
        "sections.html": "Interactive section browser",
        "formulas.html": "Formula reference and search page",
        "parameters.html": "Parameter database with experimental comparisons",
        "beginners-guide.html": "Accessible introduction to the theory",
        "foundations.html": "Mathematical and physical foundations",
        "appendices.html": "Technical appendices and derivations",
        "references.html": "Bibliography and citations",
        "simulations.html": "Simulation results and visualizations",
        "visualization-index.html": "Interactive visualization gallery",
        "philosophical-implications.html": "Philosophical discussion and implications",

        # JavaScript - Core rendering
        "pm-paper-renderer.js": "Main paper rendering engine with block processing",
        "pm-section-renderer.js": "Section content renderer with formula integration",
        "pm-section-loader.js": "Dynamic section loading and navigation",
        "pm-formula-renderer.js": "Academic formula display with LaTeX support",
        "pm-formula-loader.js": "Formula data loader and cache manager",
        "pm-parameter-component.js": "Parameter display component",
        "pm-parameter-table.js": "Interactive parameter comparison tables",
        "pm-beginner-guide-loader.js": "Beginner guide content loader",
        "pm-foundations-loader.js": "Foundations page content loader",

        # JavaScript - Components
        "pm-formula-component.js": "Reusable formula display component",
        "pm-header.js": "Site header and navigation component",
        "pm-tooltip-system.js": "Interactive tooltip system for parameters",
        "pm-paper-tooltips.js": "Paper-specific tooltip integration",
        "pm-paper-param-processor.js": "Parameter reference processor for paper",
        "pm-paper-tooltips-integration.js": "Tooltip integration with paper renderer",
        "pm-paper-renderer-blocks-patch.js": "Block rendering enhancements",
        "pm-citations.js": "Citation management and display",

        # JavaScript - Data
        "pm-parameter-schema.js": "Parameter data schema definitions",
        "pm-parameter-data.js": "Parameter metadata and descriptions",
        "pm-constants-loader.js": "Physical constants loader",
        "pm-template-engine.js": "Content template processor",

        # JavaScript - Theory
        "theory-constants.js": "Theory-specific physical constants",
        "theory-constants-enhanced.js": "Enhanced constants with metadata",
        "theory-computations.js": "Theory computation functions",
        "theory-derivations.js": "Mathematical derivation utilities",
        "pm-validation-stats.js": "Validation statistics processor",
        "validation-stats.js": "Validation data utilities",
        "simulation-stats.js": "Simulation results processor",

        # JavaScript - Formulas
        "formula-registry.js": "Formula registration and lookup system",
        "formula-database.js": "Formula database with metadata",
        "formula-definitions.js": "Formula LaTeX definitions",
        "formula-expansion.js": "Formula expansion and detail views",

        # JavaScript - Content
        "content-templates.js": "Reusable content templates",

        # JavaScript - Utilities
        "pm-param-paper.js": "Paper parameter integration utilities",
        "pm-foundation-page.js": "Foundations page utilities",

        # CSS
        "styles.css": "Main stylesheet with base styles",
        "pm-common.css": "Common UI components and utilities",
        "pm-glass-theme.css": "Glass morphism visual theme",
        "pm-scientific-typography.css": "Academic typography and formatting",
        "pm-section-paper.css": "Section and paper page styles",
        "pm-tooltip.css": "Tooltip visual styles",
        "pm-paper-tooltips.css": "Paper-specific tooltip styles",
        "pm-header.css": "Header component styles",
        "pm-citations.css": "Citation formatting styles",
        "formula-metadata.css": "Formula metadata display styles",
        "formula-display-fix.css": "Formula rendering fixes",
        "formula-hover.css": "Formula hover interaction styles",
        "mobile-responsive.css": "Mobile device optimizations",
        "styles-mobile-enhanced.css": "Enhanced mobile styles",
        "desktop-optimizations.css": "Desktop display optimizations",

        # JSON Data
        "theory_output.json": "Complete theory output with all predictions",
        "formulas.json": "Formula database with LaTeX and metadata",
        "parameters.json": "Parameter values with experimental comparisons",
        "sections.json": "Section content and structure",
        "metadata.json": "Paper metadata and configuration",
        "beginner-guide.json": "Beginner guide content data",
        "index.json": "Site index and navigation data",
        "statistics.json": "Theory validation statistics"
    }

    return descriptions.get(filename, f"{category} file: {filename}")


def copy_files_and_create_manifest():
    """Copy all website files and generate manifest."""
    print("Creating Zenodo Website Export Package...")
    print(f"Target directory: {ZENODO_WEBSITE_DIR}")
    print()

    # Create base directory
    ZENODO_WEBSITE_DIR.mkdir(parents=True, exist_ok=True)

    manifest = {
        "package_name": "Principia Metaphysica - Interactive Website",
        "package_version": "1.0.0",
        "created": datetime.now().isoformat() + "Z",
        "description": "Complete interactive website for Principia Metaphysica theory, including all HTML pages, JavaScript components, CSS styles, and data files.",
        "files": []
    }

    total_files = 0
    total_size = 0

    # Copy files by category
    for category, files in FILES_TO_COPY.items():
        if category == "root":
            target_dir = ZENODO_WEBSITE_DIR
            source_dir = BASE_DIR
        else:
            target_dir = ZENODO_WEBSITE_DIR / category
            source_dir = BASE_DIR / category
            target_dir.mkdir(exist_ok=True)

        print(f"Processing {category}/ ...")

        for filename in files:
            source_file = source_dir / filename
            target_file = target_dir / filename

            if not source_file.exists():
                print(f"  WARNING: {source_file} not found, skipping")
                continue

            # Copy file
            shutil.copy2(source_file, target_file)

            # Get file info
            file_size = target_file.stat().st_size
            checksum = calculate_sha256(target_file)

            # Determine relative path
            if category == "root":
                rel_path = filename
            else:
                rel_path = f"{category}/{filename}"

            # Add to manifest
            file_info = {
                "path": rel_path,
                "size": file_size,
                "sha256": checksum,
                "description": get_file_description(category, filename)
            }
            manifest["files"].append(file_info)

            total_files += 1
            total_size += file_size

            print(f"  [OK] {filename} ({file_size:,} bytes)")

    # Add summary to manifest
    manifest["summary"] = {
        "total_files": total_files,
        "total_size": total_size,
        "total_size_mb": round(total_size / (1024 * 1024), 2)
    }

    # Write manifest
    manifest_path = ZENODO_WEBSITE_DIR / "website_manifest.json"
    with open(manifest_path, 'w', encoding='utf-8') as f:
        json.dump(manifest, f, indent=2, ensure_ascii=False)

    print()
    print("=" * 70)
    print(f"[SUCCESS] Website package created successfully!")
    print(f"  Total files: {total_files}")
    print(f"  Total size: {total_size:,} bytes ({manifest['summary']['total_size_mb']} MB)")
    print(f"  Location: {ZENODO_WEBSITE_DIR}")
    print(f"  Manifest: {manifest_path}")
    print("=" * 70)

    return manifest


def create_readme():
    """Create README for the website package."""
    readme_content = """# Principia Metaphysica - Interactive Website Archive

This package contains the complete interactive website for the Principia Metaphysica theory.

## Contents

- **index.html**: Main landing page
- **Pages/**: Individual page templates
  - paper.html - Full academic paper
  - sections.html - Section browser
  - formulas.html - Formula reference
  - parameters.html - Parameter database
  - beginners-guide.html - Accessible introduction
  - foundations.html - Mathematical foundations
  - appendices.html - Technical appendices
  - references.html - Bibliography
  - simulations.html - Simulation results
  - visualization-index.html - Visualization gallery
  - philosophical-implications.html - Philosophical discussion

- **js/**: JavaScript components and utilities
  - Core rendering engines (paper, section, formula renderers)
  - Interactive components (tooltips, parameters, citations)
  - Data loaders and processors
  - Theory computations and validation

- **css/**: Stylesheets
  - Base styles and theme
  - Component-specific styles
  - Mobile and desktop optimizations

- **AutoGenerated/**: JSON data files
  - theory_output.json - Complete theory predictions
  - formulas.json - Formula database
  - parameters.json - Parameter values
  - sections.json - Section content
  - metadata.json - Paper metadata
  - Other supporting data files

## Usage

To view the website locally:

1. Extract all files maintaining directory structure
2. Open `index.html` in a modern web browser
3. Navigate through the interactive interface

## Requirements

- Modern web browser with JavaScript enabled
- Internet connection for MathJax LaTeX rendering
- Screen resolution: 1024x768 or higher recommended

## File Integrity

All files include SHA-256 checksums in `website_manifest.json` for verification.

## License

See LICENSE file in parent directory.

## Citation

See CITATION.cff in parent directory for proper citation format.
"""

    readme_path = ZENODO_WEBSITE_DIR / "README.md"
    with open(readme_path, 'w', encoding='utf-8') as f:
        f.write(readme_content)

    print(f"[OK] README created: {readme_path}")


if __name__ == "__main__":
    manifest = copy_files_and_create_manifest()
    create_readme()
    print("\nWebsite export package ready for Zenodo upload!")
