#!/usr/bin/env python3
"""
Fix formula references in sections.

This script addresses the critical issue where formula blocks in sections
use plain text 'content' instead of 'formulaId' references to the formula
metadata in theory_output.json.

Critical Issues Fixed:
1. Replace plain text formula blocks with formulaId references
2. Add 'section' field to formula metadata
3. Validate all formula references
"""

import json
import re
from pathlib import Path
from typing import Dict, List, Tuple

# Load theory_output.json
THEORY_OUTPUT_PATH = Path('AutoGenerated/theory_output.json')

def load_data():
    """Load theory output data."""
    with open(THEORY_OUTPUT_PATH, encoding='utf-8') as f:
        return json.load(f)

def save_data(data):
    """Save theory output data."""
    with open(THEORY_OUTPUT_PATH, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"✓ Saved to {THEORY_OUTPUT_PATH}")

def extract_formula_id_from_label(label: str) -> str:
    """Generate formula ID from label."""
    if not label:
        return None

    # Remove parentheses and "Eq." prefix
    clean = label.strip()
    clean = re.sub(r'^\(|\)$', '', clean)
    clean = re.sub(r'^Eq\.\s*', '', clean, flags=re.IGNORECASE)

    # Convert to ID format
    # "(2.1)" -> "eq-2-1"
    # "Main Equation" -> "main-equation"
    if re.match(r'^\d+\.\d+$', clean):
        return f"eq-{clean.replace('.', '-')}"
    else:
        return clean.lower().replace(' ', '-')

def find_matching_formula(content: str, formulas: Dict, section_id: str) -> str:
    """Find formula ID that matches content text."""
    # First try: match by plain text
    for fid, formula in formulas.items():
        plain_text = formula.get('plain_text', '')
        if plain_text and plain_text in content:
            return fid

    # Second try: match by LaTeX (convert to plain)
    content_normalized = content.replace(' ', '').lower()
    for fid, formula in formulas.items():
        latex = formula.get('latex', '')
        latex_normalized = latex.replace(' ', '').replace('\\', '').lower()
        if latex_normalized and latex_normalized in content_normalized:
            return fid

    # Third try: match by description keywords
    content_lower = content.lower()
    for fid, formula in formulas.items():
        desc = formula.get('description', '').lower()
        if desc and len(desc) > 20:
            # Check if key words from description appear in content
            desc_words = set(desc.split()[:5])  # First 5 words
            content_words = set(content_lower.split())
            if len(desc_words & content_words) >= 3:
                return fid

    return None

def add_section_to_formulas(data: Dict):
    """Add 'section' field to all formulas based on formulaRefs."""
    formulas = data.get('formulas', {})
    sections = data.get('sections', {})

    print("\n" + "="*80)
    print("ADDING SECTION FIELD TO FORMULAS")
    print("="*80)

    updated_count = 0

    for section_id, section in sections.items():
        formula_refs = section.get('formulaRefs', [])

        for fid in formula_refs:
            if fid in formulas:
                formulas[fid]['section'] = section_id
                updated_count += 1
                print(f"  {fid} -> section {section_id}")

    print(f"\n✓ Updated {updated_count} formulas with section field")
    return updated_count

def fix_formula_blocks(data: Dict):
    """Fix formula blocks in all sections."""
    formulas = data.get('formulas', {})
    sections = data.get('sections', {})

    print("\n" + "="*80)
    print("FIXING FORMULA BLOCKS IN SECTIONS")
    print("="*80)

    total_fixed = 0
    total_blocks = 0

    for section_id, section in sorted(sections.items(), key=lambda x: (not x[0].isdigit(), x[0])):
        title = section.get('title', 'Unknown')
        content_blocks = section.get('contentBlocks', [])

        fixed_in_section = 0
        formula_blocks = [b for b in content_blocks if b.get('type') in ['equation', 'formula']]

        if not formula_blocks:
            continue

        print(f"\nSection {section_id}: {title}")
        print(f"  Formula blocks: {len(formula_blocks)}")

        for i, block in enumerate(content_blocks):
            if block.get('type') not in ['equation', 'formula']:
                continue

            total_blocks += 1

            # Check if already has formulaId
            if block.get('formulaId'):
                print(f"    [{i}] Already has formulaId: {block['formulaId']}")
                continue

            # Check if has formula_id (lowercase)
            if block.get('formula_id'):
                # Fix casing
                block['formulaId'] = block.pop('formula_id')
                block['type'] = 'equation'
                fixed_in_section += 1
                total_fixed += 1
                print(f"    [{i}] Fixed casing: formula_id -> formulaId: {block['formulaId']}")
                continue

            # Try to find matching formula
            content = block.get('content', '')
            label = block.get('label', '')

            # Try matching by content
            matched_fid = find_matching_formula(content, formulas, section_id)

            if matched_fid:
                # Replace content block with formulaId reference
                block.clear()
                block['type'] = 'equation'
                block['formulaId'] = matched_fid
                if label:
                    block['label'] = label
                fixed_in_section += 1
                total_fixed += 1
                print(f"    [{i}] Matched by content -> {matched_fid}")
            else:
                # No match found - keep as-is but warn
                print(f"    [{i}] ⚠️  No match found for: {content[:60]}...")
                print(f"           Label: {label}")

        if fixed_in_section > 0:
            print(f"  ✓ Fixed {fixed_in_section} blocks in section {section_id}")

    print(f"\n" + "="*80)
    print(f"SUMMARY")
    print(f"="*80)
    print(f"  Total formula blocks found: {total_blocks}")
    print(f"  Total blocks fixed: {total_fixed}")
    print(f"  Remaining unfixed: {total_blocks - total_fixed}")

    return total_fixed

def validate_references(data: Dict):
    """Validate all formula references."""
    formulas = data.get('formulas', {})
    sections = data.get('sections', {})

    print("\n" + "="*80)
    print("VALIDATING FORMULA REFERENCES")
    print("="*80)

    errors = []

    for section_id, section in sections.items():
        formula_refs = section.get('formulaRefs', [])

        for fid in formula_refs:
            if fid not in formulas:
                errors.append(f"Section {section_id} references missing formula: {fid}")

    if errors:
        print("\n❌ ERRORS FOUND:")
        for err in errors:
            print(f"  - {err}")
        return False
    else:
        print("✓ All formula references are valid")
        return True

def main():
    """Main fix script."""
    print("="*80)
    print("FORMULA REFERENCE FIX SCRIPT")
    print("="*80)

    # Load data
    print("\nLoading theory_output.json...")
    data = load_data()

    formulas = data.get('formulas', {})
    sections = data.get('sections', {})

    print(f"  Formulas: {len(formulas)}")
    print(f"  Sections: {len(sections)}")

    # Step 1: Add section field to formulas
    section_updates = add_section_to_formulas(data)

    # Step 2: Fix formula blocks in sections
    fixed_blocks = fix_formula_blocks(data)

    # Step 3: Validate all references
    valid = validate_references(data)

    # Save
    print("\n" + "="*80)
    print("SAVING CHANGES")
    print("="*80)

    if fixed_blocks > 0 or section_updates > 0:
        # Create backup first
        backup_path = THEORY_OUTPUT_PATH.with_suffix('.json.backup')
        with open(backup_path, 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=2, ensure_ascii=False)
        print(f"  Created backup: {backup_path}")

        # Save changes
        save_data(data)

        print("\n" + "="*80)
        print("✓ FIX COMPLETE")
        print("="*80)
        print(f"  Section field updates: {section_updates}")
        print(f"  Formula blocks fixed: {fixed_blocks}")
        print(f"  Validation: {'✓ PASS' if valid else '❌ FAIL'}")
    else:
        print("  No changes needed - already correct!")

if __name__ == '__main__':
    main()
