"""
Generate validation report for Sections 4-5 schema compliance
"""
import json

# Generate comprehensive validation report
with open('h:/Github/PrincipiaMetaphysica/AutoGenerated/theory_output.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

report = {
    'validation_date': '2025-12-29',
    'sections_reviewed': ['4', '5'],
    'findings': {
        'section_4': {
            'title': 'Neutrino Mixing from G2 Geometry',
            'schema_compliance': {},
            'missing_content': [],
            'present_content': []
        },
        'section_5': {
            'title': 'Multi-Sector Cosmological Dynamics',
            'schema_compliance': {},
            'missing_content': [],
            'present_content': []
        }
    },
    'critical_issues': [],
    'warnings': []
}

sections = data.get('sections', {})
formulas = data.get('formulas', {})
params = data.get('parameters', {})

# Section 4 validation
section_4 = sections.get('4', {})
s4_formulas = section_4.get('formula_refs', [])
s4_params = section_4.get('param_refs', [])

# Check Section 4 formulas
for fid in s4_formulas:
    f = formulas.get(fid, {})
    has_all = all([f.get('id'), f.get('label'), f.get('latex'), f.get('derivation')])
    report['findings']['section_4']['schema_compliance'][fid] = {
        'compliant': has_all,
        'has_id': bool(f.get('id')),
        'has_label': bool(f.get('label')),
        'has_latex': bool(f.get('latex')),
        'has_derivation': bool(f.get('derivation'))
    }

# Check Section 4 parameters
for pid in s4_params:
    p = params.get(pid, {})
    has_required = all([p.get('value') is not None, p.get('status')])
    report['findings']['section_4']['schema_compliance'][pid] = {
        'compliant': has_required,
        'has_value': p.get('value') is not None,
        'has_status': bool(p.get('status')),
        'has_experimental_bound': bool(p.get('experimental_bound'))
    }

# Section 5 validation
section_5 = sections.get('5', {})
s5_formulas = section_5.get('formula_refs', [])
s5_params = section_5.get('param_refs', [])

# Check Section 5 formulas
for fid in s5_formulas:
    f = formulas.get(fid, {})
    has_all = all([f.get('id'), f.get('label'), f.get('latex'), f.get('derivation')])
    report['findings']['section_5']['schema_compliance'][fid] = {
        'compliant': has_all,
        'has_id': bool(f.get('id')),
        'has_label': bool(f.get('label')),
        'has_latex': bool(f.get('latex')),
        'has_derivation': bool(f.get('derivation'))
    }

# Check Section 5 parameters
for pid in s5_params:
    p = params.get(pid, {})
    has_required = all([p.get('value') is not None, p.get('status')])
    report['findings']['section_5']['schema_compliance'][pid] = {
        'compliant': has_required,
        'has_value': p.get('value') is not None,
        'has_status': bool(p.get('status')),
        'has_experimental_bound': bool(p.get('experimental_bound'))
    }

# Check for missing injections
# 1. m_p/m_e from mass_ratio_v16_1.py
mass_ratio_found = False
for k in params.keys():
    if 'proton' in k.lower() and 'electron' in k.lower() and 'ratio' in k.lower():
        mass_ratio_found = True
        report['findings']['section_4']['present_content'].append({
            'type': 'parameter',
            'name': k,
            'value': params[k].get('value'),
            'source': 'mass_ratio_v16_1.py (expected)'
        })

if not mass_ratio_found:
    report['critical_issues'].append({
        'section': '4',
        'issue': 'MISSING m_p/m_e derivation',
        'expected_source': 'simulations/v16/fermion/mass_ratio_v16_1.py',
        'expected_parameter': 'fermion.proton_electron_ratio or similar',
        'expected_value': '~1836.15',
        'severity': 'CRITICAL',
        'description': 'The mass_ratio_v16_1.py file computes m_p/m_e from G2 geometry but this result is not injected into Section 4'
    })
    report['findings']['section_4']['missing_content'].append({
        'type': 'parameter',
        'name': 'proton-electron mass ratio',
        'expected_value': '~1836.15',
        'source_file': 'mass_ratio_v16_1.py'
    })

# 2. Proton decay in Section 4
proton_decay_in_s4 = any('proton' in str(fid).lower() for fid in s4_formulas)
if not proton_decay_in_s4:
    report['warnings'].append({
        'section': '4',
        'issue': 'Proton decay formulas not in Section 4',
        'note': 'Proton decay formulas exist in database but are not referenced in Section 4 (Fermion Sector)',
        'existing_formulas': ['proton-lifetime', 'proton-decay-rate', 'proton-decay-lifetime'],
        'severity': 'WARNING'
    })

# 3. S8 from s8_bulk_viscosity_solver.py
s8_predicted = params.get('cosmology.s8_pm_predicted')
if s8_predicted:
    report['findings']['section_5']['present_content'].append({
        'type': 'parameter',
        'name': 'cosmology.s8_pm_predicted',
        'value': s8_predicted.get('value'),
        'source': 's8_bulk_viscosity_solver.py (likely)',
        'validation': 'PRESENT'
    })
else:
    report['warnings'].append({
        'section': '5',
        'issue': 'S8 prediction parameter not found with expected name',
        'expected_source': 's8_bulk_viscosity_solver.py',
        'expected_parameter': 'cosmology.s8_pm_predicted',
        'severity': 'WARNING'
    })

# 4. w0 = -11/13 from dark_energy_v16_0.py
w0_derived = params.get('cosmology.w0_derived')
if w0_derived:
    w0_value = w0_derived.get('value')
    expected_w0 = -11/13
    match = abs(w0_value - expected_w0) < 1e-10
    report['findings']['section_5']['present_content'].append({
        'type': 'parameter',
        'name': 'cosmology.w0_derived',
        'value': w0_value,
        'expected': expected_w0,
        'match': match,
        'source': 'dark_energy_v16_0.py',
        'validation': 'PRESENT and CORRECT' if match else 'PRESENT but VALUE MISMATCH'
    })
    if not match:
        report['warnings'].append({
            'section': '5',
            'issue': 'w0_derived value mismatch',
            'expected': expected_w0,
            'actual': w0_value,
            'difference': abs(w0_value - expected_w0),
            'severity': 'WARNING'
        })
else:
    report['critical_issues'].append({
        'section': '5',
        'issue': 'MISSING w0 derivation',
        'expected_source': 'dark_energy_v16_0.py',
        'expected_parameter': 'cosmology.w0_derived',
        'expected_value': -11/13,
        'severity': 'CRITICAL'
    })

# Check for H0
h0_param = params.get('desi.H0')
if h0_param:
    report['findings']['section_5']['present_content'].append({
        'type': 'parameter',
        'name': 'desi.H0',
        'value': h0_param.get('value'),
        'note': 'H0 parameter exists (experimental reference)',
        'validation': 'PRESENT'
    })

# Check for neutrino mixing in Section 4
neutrino_params_present = sum(1 for p in s4_params if 'neutrino' in p.lower())
if neutrino_params_present > 0:
    report['findings']['section_4']['present_content'].append({
        'type': 'parameter_group',
        'name': 'neutrino mixing parameters',
        'count': neutrino_params_present,
        'validation': 'PRESENT'
    })

# Summary statistics
report['summary'] = {
    'total_issues': len(report['critical_issues']) + len(report['warnings']),
    'critical_issues': len(report['critical_issues']),
    'warnings': len(report['warnings']),
    'section_4': {
        'formulas_checked': len(s4_formulas),
        'formulas_compliant': sum(1 for fid in s4_formulas if report['findings']['section_4']['schema_compliance'].get(fid, {}).get('compliant', False)),
        'parameters_checked': len(s4_params),
        'parameters_compliant': sum(1 for pid in s4_params if report['findings']['section_4']['schema_compliance'].get(pid, {}).get('compliant', False)),
        'missing_content_count': len(report['findings']['section_4']['missing_content']),
        'present_content_count': len(report['findings']['section_4']['present_content'])
    },
    'section_5': {
        'formulas_checked': len(s5_formulas),
        'formulas_compliant': sum(1 for fid in s5_formulas if report['findings']['section_5']['schema_compliance'].get(fid, {}).get('compliant', False)),
        'parameters_checked': len(s5_params),
        'parameters_compliant': sum(1 for pid in s5_params if report['findings']['section_5']['schema_compliance'].get(pid, {}).get('compliant', False)),
        'missing_content_count': len(report['findings']['section_5']['missing_content']),
        'present_content_count': len(report['findings']['section_5']['present_content'])
    }
}

# Write report
with open('h:/Github/PrincipiaMetaphysica/SECTIONS_4_5_VALIDATION_REPORT.json', 'w', encoding='utf-8') as f:
    json.dump(report, f, indent=2, ensure_ascii=False)

print('='*70)
print('VALIDATION REPORT FOR SECTIONS 4-5')
print('='*70)
print(f'\nSummary:')
print(f'  Critical Issues: {report["summary"]["critical_issues"]}')
print(f'  Warnings: {report["summary"]["warnings"]}')
print(f'\nSection 4 (Fermion Sector):')
print(f'  Formulas: {report["summary"]["section_4"]["formulas_compliant"]}/{report["summary"]["section_4"]["formulas_checked"]} compliant')
print(f'  Parameters: {report["summary"]["section_4"]["parameters_compliant"]}/{report["summary"]["section_4"]["parameters_checked"]} compliant')
print(f'  Missing content items: {report["summary"]["section_4"]["missing_content_count"]}')
print(f'\nSection 5 (Cosmology):')
print(f'  Formulas: {report["summary"]["section_5"]["formulas_compliant"]}/{report["summary"]["section_5"]["formulas_checked"]} compliant')
print(f'  Parameters: {report["summary"]["section_5"]["parameters_compliant"]}/{report["summary"]["section_5"]["parameters_checked"]} compliant')
print(f'  Missing content items: {report["summary"]["section_5"]["missing_content_count"]}')

print('\n' + '='*70)
print('CRITICAL ISSUES:')
print('='*70)
for issue in report['critical_issues']:
    print(f"\nSection {issue['section']}: {issue['issue']}")
    print(f"  Source: {issue.get('expected_source', 'N/A')}")
    print(f"  Expected: {issue.get('expected_parameter', 'N/A')}")
    if 'description' in issue:
        print(f"  Details: {issue['description']}")

print('\n' + '='*70)
print('WARNINGS:')
print('='*70)
for warning in report['warnings']:
    print(f"\nSection {warning['section']}: {warning['issue']}")
    if 'note' in warning:
        print(f"  Note: {warning['note']}")

print('\n' + '='*70)
print('Report written to: SECTIONS_4_5_VALIDATION_REPORT.json')
print('='*70)
