"""
generate_js_constants.py - Auto-generate JavaScript constants from config.py

This script reads ALL parameter values from config.py and generates
js/theory-constants.js so that HTML webpages display the same values
that SimulateTheory.py uses for calculations.

SINGLE SOURCE OF TRUTH: config.py

Usage:
    python generate_js_constants.py

This will overwrite js/theory-constants.js with current config.py values.
"""

import sys
from datetime import datetime

# Import all configuration classes
try:
    from config import (
        FundamentalConstants as FC,
        PhenomenologyParameters as PP,
        MultiTimeParameters as MTP,
        ModuliParameters as MP,
        LandscapeParameters as LP,
        ComputationalSettings as CS,
        V61Predictions as V61,
        FRTTauParameters as FRTP,
        ThermalTimeParameters as TTP,
        GaugeUnificationParameters as GUP,
        NeutrinoParameters as NP,
        CMBBubbleParameters as CMB
    )
    print("SUCCESS: Imported config.py")
except ImportError as e:
    print(f"ERROR: Could not import config.py: {e}")
    sys.exit(1)

# Generate JavaScript file content
js_content = f"""/**
 * theory-constants.js - Principia Metaphysica Theory Constants
 *
 * AUTO-GENERATED from config.py by generate_js_constants.py
 * DO NOT EDIT THIS FILE MANUALLY - Edit config.py instead!
 *
 * Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
 * Framework Version: v6.1
 *
 * To regenerate after editing config.py:
 *   python generate_js_constants.py
 */

const TheoryConstants = {{

    // ================================================================
    // DIMENSIONAL STRUCTURE
    // ================================================================

    dimensions: {{
        full: {FC.D_BULK},                    // Full theory dimensionality
        signature: {{ space: 24, time: 2 }},   // (24,2) signature
        effective: {FC.D_INTERNAL},            // Gauge-fixed shadow dimensionality
        effectiveSignature: {{ space: 12, time: 1 }},  // (12,1) effective
        observable: {FC.D_OBSERVED},           // Macroscopic spacetime

        // Brane hierarchy
        nBranes: {FC.N_BRANES},                // Number of D-branes
        spatialDimsPerBrane: {FC.SPATIAL_DIMS}, // Spatial dimensions per brane
        timeDims: {FC.TIME_DIMS},              // Shared time dimension

        // Derived
        get dEff() {{ return 12; }},           // Effective spatial dimensions for MEP
        get totalCheck() {{ return this.nBranes * this.spatialDimsPerBrane + this.timeDims; }} // Should = 13
    }},

    // ================================================================
    // SPINOR STRUCTURE
    // ================================================================

    spinors: {{
        full26D: {FC.pneuma_dimension_full()},      // 8192 components in Cl(24,2)
        effective13D: {FC.pneuma_dimension_reduced()}, // 64 components after Sp(2,R) gauge fixing

        // Clifford algebras
        clifford26D: "Cl(24,2)",
        clifford13D: "Cl(12,1)",
        clifford4D: "Cl(3,1)",

        get reductionRatio() {{ return this.full26D / this.effective13D; }}  // 128
    }},

    // ================================================================
    // TOPOLOGY & GENERATIONS
    // ================================================================

    topology: {{
        // Calabi-Yau Hodge numbers
        h11: {FC.HODGE_H11},
        h21: {FC.HODGE_H21},
        h31: {FC.HODGE_H31},

        // Euler characteristic
        chiEffective: {FC.euler_characteristic_effective()},  // 144 (effective)

        // Flux quantization
        fluxReduction: {FC.FLUX_REDUCTION},

        // Generations
        generations: {FC.fermion_generations()},  // 3 (exact match with SM)

        // SO(10) representations
        adjointDim: {GUP.DIM_ADJOINT},      // 45
        spinorDim: {GUP.DIM_SPINOR},        // 16
    }},

    // ================================================================
    // FUNDAMENTAL SCALES
    // ================================================================

    fundamentalScales: {{
        mPlanck: {PP.M_PLANCK},          // GeV (PDG 2024)
        mStar: {PP.M_STAR},              // GeV (13D fundamental scale)
        mGUT: {GUP.M_GUT},               // GeV (grand unification)
        alphaGUT: {GUP.ALPHA_GUT},       // GUT fine structure constant
        alphaEM: {PP.ALPHA_EM},          // QED fine structure constant
    }},

    // ================================================================
    // DARK ENERGY (DESI 2024 Compatible)
    // ================================================================

    darkEnergy: {{
        // Theoretical values (derived from MEP + two-time)
        w0Numerator: {PP.W0_NUMERATOR},
        w0Denominator: {PP.W0_DENOMINATOR},
        w0: {PP.w0_value()},             // -11/13 ≈ -0.846
        wa: {PP.WA_EVOLUTION},           // -0.75 (exact DESI match!)

        // Observational values (DESI 2024)
        w0Observed: -0.827,
        w0Error: 0.063,
        waObserved: -0.75,
        waError: 0.3,

        // Cosmological parameters
        omegaLambda: {PP.OMEGA_LAMBDA},   // Dark energy density
        omegaMatter: {PP.OMEGA_MATTER},   // Matter density
        omegaBaryon: {PP.OMEGA_BARYON},   // Baryon density
        H0: {PP.H0},                      // km/s/Mpc
    }},

    // ================================================================
    // THERMAL TIME HYPOTHESIS
    // ================================================================

    thermalTime: {{
        alphaT: {TTP.ALPHA_T_CANONICAL},     // 2.7 (Z₂-corrected canonical)
        alphaTBase: {TTP.ALPHA_T_BASE},      // 2.5 (without Z₂)
        z2Correction: {TTP.Z2_CORRECTION},   // 0.2

        // Epoch-dependent values
        alphaTz0: {TTP.ALPHA_T_Z0},          // 1.67 (Λ-dominated, z=0)
        alphaTz1: {TTP.ALPHA_T_Z1},          // 2.38 (transition, z=1)
        alphaTz2: {TTP.ALPHA_T_Z2},          // 2.59 (matter-dominated, z=2)
        alphaTHighZ: {TTP.ALPHA_T_HIGH_Z},   // 2.7 (deep matter, z>3)

        get waFormula() {{ return `w_a = w_0 × α_T / 3 ≈ -0.846 × 2.7 / 3 ≈ -0.76`; }}
    }},

    // ================================================================
    // F(R,T,τ) MODIFIED GRAVITY
    // ================================================================

    modifiedGravity: {{
        alphaRSquared: {FRTP.ALPHA_R_SQUARED},     // [M_Pl^-2] 1-loop quantum correction
        betaMatter: {FRTP.BETA_MATTER},            // Dimensionless, breathing mode
        gammaMixed: {FRTP.GAMMA_MIXED},            // [M_Pl^-2] RT coupling
        deltaOrthoTime: {FRTP.DELTA_ORTHO_TIME},   // [seconds] ∂_τ coefficient

        phi0Breathing: {FRTP.PHI_0_BREATHING_MODE}, // Breathing mode VEV
        nEffPneuma: {FRTP.N_EFF_PNEUMA_LOOP},       // Effective DOF in loops
    }},

    // ================================================================
    // MULTI-TIME STRUCTURE
    // ================================================================

    multiTime: {{
        // Coupling constants
        g: {MTP.G_COUPLING},                 // 0.1 (multi-time coupling)
        eFermi: {MTP.E_FERMI},               // 1.0 TeV (Fermi energy)

        // Gravitational wave dispersion
        xi: {MTP.XI_QUADRATIC},              // 10^10 (quadratic coefficient)
        eta: {MTP.eta_linear()},             // 0.1 (linear: g/E_F)
        etaBoosted: {V61.ETA_BOOSTED},       // 10^9 (asymptotic safety)

        // Orthogonal time parameters
        deltaTOrtho: {MTP.DELTA_T_ORTHO},    // 10^-18 seconds
        rOrtho: {MTP.R_ORTHO},               // Normalized radius

        // LISA frequencies
        kLISAMin: {MTP.K_LISA_MIN},          // 10^-4 Hz
        kLISATypical: {MTP.K_LISA_TYPICAL},  // 10^-3 Hz
        kLISAMax: {MTP.K_LISA_MAX},          // 10^-1 Hz

        // Mirror sector
        thetaMirror: {MTP.THETA_MIRROR_DEFAULT},  // 0.0 radians (no mixing)
        theta45Deg: {MTP.THETA_EXAMPLE_45DEG},    // π/4 for examples
    }},

    // ================================================================
    // MODULI STABILIZATION (KKLT)
    // ================================================================

    moduli: {{
        // SUSY breaking
        fTerm: {MP.F_TERM_NORMALIZED},       // Normalized F-term
        fTermPhysical: {MP.F_TERM_PHYSICAL}, // 10^10 GeV^2

        // Swampland parameters
        aSwampland: {MP.a_swampland()},      // √(26/13) = √2 ≈ 1.414
        swamplandBound: {MP.SWAMPLAND_BOUND}, // √(2/3) ≈ 0.816

        // Potential terms
        kappaUplift: {MP.KAPPA_UPLIFT},      // 1.0
        bInstanton: {MP.B_INSTANTON},        // 1.0
        muPeriodic: {MP.MU_PERIODIC},        // 0.5

        // Condensate
        lambdaCoupling: {MP.LAMBDA_COUPLING}, // 0.5 TeV^-2
        vVEV: {MP.V_VEV},                     // 2.0 TeV
        tOrthoNorm: {MP.T_ORTHO_NORMALIZED},  // 1.0

        condensateGap: {MP.condensate_gap()}, // ~0.909 TeV
    }},

    // ================================================================
    // LANDSCAPE & MULTIVERSE
    // ================================================================

    landscape: {{
        // Vacuum counting
        nVacExponent: {LP.N_VAC_EXPONENT},      // 500 (N_vac ~ 10^500)
        landscapeEntropy: {LP.landscape_entropy()}, // ~1151.29

        // Coleman-De Luccia tunneling
        sigmaTension: {LP.SIGMA_TENSION},       // Normalized
        deltaVMultiverse: {LP.DELTA_V_MULTIVERSE}, // Normalized

        // CMB bubble collisions
        bubbleRadiusMpc: {LP.BUBBLE_RADIUS_MPC},   // 100 Mpc
        cmbTemperatureUK: {LP.CMB_TEMPERATURE_UK}, // 100 μK

        get euclideanAction() {{ return {LP.euclidean_action()}; }},
        get tunnelingRate() {{ return {LP.tunneling_rate()}; }},
    }},

    // ================================================================
    // v6.1 NEW PREDICTIONS (Testable!)
    // ================================================================

    v61Predictions: {{
        // Kaluza-Klein modes (LHC-testable)
        mKKCentral: {V61.M_KK_CENTRAL},       // 5.0 TeV
        mKKMin: {V61.M_KK_MIN},               // 3.0 TeV (95% CL)
        mKKMax: {V61.M_KK_MAX},               // 7.0 TeV (95% CL)
        mKKCurrentBound: {V61.M_KK_CURRENT_BOUND}, // 3.5 TeV (ATLAS/CMS)

        // GW dispersion (LISA-testable)
        etaBaseline: {V61.ETA_BASELINE},      // 0.1
        etaBoosted: {V61.ETA_BOOSTED},        // 10^9
        etaEffectMin: {V61.ETA_EFFECT_MIN},   // 10^-29
        etaEffectMax: {V61.ETA_EFFECT_MAX},   // 10^-20

        // SME Lorentz violation (Collider-testable)
        cMuNuFermion: {V61.C_MU_NU_FERMION},  // 10^-5
        cEMuRatio: {V61.C_E_MU_RATIO},        // 2×10^-5
        sMuNuGW: {V61.S_MU_NU_GW},            // 10^-15

        // Quantum nonlocality (Lab-testable)
        chshDeltaOrtho: {V61.CHSH_DELTA_ORTHO}, // 10^-5
        chshPredicted: {V61.CHSH_PREDICTED},    // 2.828028
        chshStatisticsRequired: {V61.CHSH_STATISTICS_REQUIRED}, // 10^11

        // Mirror sector (CMB-testable)
        deltaNEffMin: {V61.DELTA_N_EFF_MIN},    // 0.08
        deltaNEffMax: {V61.DELTA_N_EFF_MAX},    // 0.16
        deltaNEffCentral: {V61.DELTA_N_EFF_CENTRAL}, // 0.12
    }},

    // ================================================================
    // NEUTRINO SECTOR
    // ================================================================

    neutrinos: {{
        // Normal Hierarchy prediction (PRIMARY FALSIFICATION TEST)
        hierarchy: "{NP.HIERARCHY_PREDICTION}",  // "Normal"

        // Mass spectrum
        mNu1: {NP.M_NU_1},        // 0.001 eV
        mNu2: {NP.M_NU_2},        // 0.009 eV
        mNu3: {NP.M_NU_3},        // 0.050 eV
        sumMNu: {NP.SUM_M_NU},    // 0.060 eV (WARNING: not unique)

        // Oscillation data
        deltaMSq21: {NP.DELTA_M_SQUARED_21}, // 7.5×10^-5 eV^2
        deltaMSq31: {NP.DELTA_M_SQUARED_31}, // 2.5×10^-3 eV^2

        // Seesaw scale
        mRHNeutrino: {NP.M_RH_NEUTRINO},     // 10^14 GeV
    }},

    // ================================================================
    // CMB BUBBLE COLLISIONS
    // ================================================================

    cmbBubbles: {{
        // Gaussian random field
        sigmaCMBRMS: {CMB.SIGMA_CMB_RMS},         // 3×10^-3
        thetaSpotDeg: {CMB.THETA_SPOT_DEG},       // 1.0 degrees
        thetaSpotRad: {CMB.THETA_SPOT_RAD},       // 0.017 radians
        nMinimaDensity: {CMB.N_MINIMA_DENSITY},   // 1650 sr^-1
        skyAreaSR: {CMB.SKY_AREA_SR},             // 4π ≈ 12.566

        // Anomaly thresholds
        delta3Sigma: {CMB.DELTA_3SIGMA},          // 9×10^-3
        delta5Sigma: {CMB.DELTA_5SIGMA},          // 15×10^-3

        // Bubble signatures
        deltaDiskCollision: {CMB.DELTA_DISK_COLLISION}, // 0.1
        fNLBubble: {CMB.F_NL_BUBBLE},             // 100

        // Poisson statistics
        lambdaThreshold: {CMB.LAMBDA_FALSIFIABILITY_THRESHOLD}, // 10^-3

        kurtosisExcess: (nDisk, delta, sigma) => {{
            return 3 + nDisk * Math.pow(delta/sigma, 4);
        }}
    }},

    // ================================================================
    // PROTON DECAY
    // ================================================================

    protonDecay: {{
        tauProton: {PP.TAU_PROTON},           // 3.5×10^34 years (central)
        tauLowerBound: {PP.TAU_PROTON_LOWER}, // 1.67×10^34 years (Super-K)

        branchingRatio: (theta) => {{
            const beta = Math.cos(theta);
            return 1 / (1 + beta * beta);
        }}
    }},

    // ================================================================
    // COMPUTATIONAL SETTINGS
    // ================================================================

    computational: {{
        // QuTiP simulations
        nQutipToy: {CS.N_QUTIP_HILBERT},         // 4
        nQutipProduction: {CS.N_QUTIP_PRODUCTION}, // 10

        // Time evolution
        timeStart: {CS.TIME_START},              // 0
        timeEnd: {CS.TIME_END},                  // 10
        timeSteps: {CS.TIME_STEPS},              // 100

        // Tolerances
        toleranceUnitarity: {CS.TOLERANCE_UNITARITY},     // 10^-10
        toleranceConvergence: {CS.TOLERANCE_CONVERGENCE}, // 10^-8

        // Limits
        aLimitExponent: {CS.A_LIMIT_EXPONENT},   // 10 (exp(10) for a→∞)

        // SymPy
        sympyPrecision: {CS.SYMPY_PRECISION_DIGITS}, // 10
    }},

    // ================================================================
    // METADATA
    // ================================================================

    metadata: {{
        version: "6.1",
        lastGenerated: "{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        generatedFrom: "config.py via generate_js_constants.py",
        frameworkName: "Principia Metaphysica",

        // Validation checks
        validate: function() {{
            const checks = {{
                swampland: this.parent.moduli.aSwampland > this.parent.moduli.swamplandBound,
                generations: this.parent.topology.generations === 3,
                dimensions: this.parent.dimensions.totalCheck === 13
            }};

            const allPass = Object.values(checks).every(v => v === true);
            return {{ checks, allPass }};
        }}
    }}
}};

// Add parent reference for metadata validation
TheoryConstants.metadata.parent = TheoryConstants;

// Export for use in other JS files
if (typeof module !== 'undefined' && module.exports) {{
    module.exports = TheoryConstants;
}}

// Display configuration summary
console.log('SUCCESS: Principia Metaphysica Theory Constants loaded');
console.log(`  Framework: v${{TheoryConstants.metadata.version}}`);
console.log(`  Generated: ${{TheoryConstants.metadata.lastGenerated}}`);
console.log(`  Dimensions: 26D -> 13D -> 7D (G2) -> 6D (effective) -> 4D (observed)`);
console.log(`  Generations: ${{TheoryConstants.topology.generations}}`);
console.log(`  Swampland: a = ${{TheoryConstants.moduli.aSwampland.toFixed(3)}} > ${{TheoryConstants.moduli.swamplandBound.toFixed(3)}} PASS`);
"""

# Write to file
output_path = "js/theory-constants.js"
try:
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(js_content)
    print(f"SUCCESS: Generated {output_path}")
    print(f"  Total lines: {len(js_content.splitlines())}")
    print(f"  File size: {len(js_content)} bytes")
except Exception as e:
    print(f"ERROR: Could not write file: {e}")
    sys.exit(1)

# Validation check
print("\n=== Validation ===")
print(f"Dimensions: {FC.D_BULK}D -> {FC.D_AFTER_SP2R}D -> {FC.D_INTERNAL}D (internal) -> {FC.D_EFFECTIVE}D (effective) -> {FC.D_OBSERVED}D (observed)")
print(f"Generations: {FC.fermion_generations()}")
print(f"Swampland: a = {MP.a_swampland():.6f} > {MP.SWAMPLAND_BOUND:.6f} PASS")
print(f"w_0 = {PP.w0_value():.6f}")
print(f"m_KK = {V61.M_KK_CENTRAL} TeV")
print(f"alpha_T = {TTP.ALPHA_T_CANONICAL}")
print(f"M_GUT = {GUP.M_GUT:.2e} GeV")

print("\nSUCCESS: JavaScript constants file generated!")
print("  Run 'python SimulateTheory.py' to generate CSV with same values")
