#!/usr/bin/env python3
"""Generate comprehensive validation report for theory_output.json"""

import json
import math
from pathlib import Path
from collections import defaultdict

# Load data
with open('AutoGenerated/theory_output.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

params = data.get('parameters', {})
formulas = data.get('formulas', {})

print(f'Analyzing {len(params)} parameters and {len(formulas)} formulas...\n')

# Detailed parameter validation
param_results = {
    'total': len(params),
    'with_validation': 0,
    'missing_validation': [],
    'invalid_value': [],
    'missing_source': [],
    'missing_status': [],
    'missing_units': [],
    'derived_without_validation': [],
    'validation_status_issues': [],
    'by_source': defaultdict(list),
    'by_status': defaultdict(int)
}

for pid, p in params.items():
    # Value check
    value = p.get('value')
    if value is None or (isinstance(value, (int, float)) and (math.isnan(value) or math.isinf(value))):
        param_results['invalid_value'].append(pid)

    # Source check
    source = p.get('source', '').strip()
    if not source:
        param_results['missing_source'].append(pid)
    else:
        param_results['by_source'][source].append(pid)

    # Status check
    status = p.get('status', '').strip()
    if not status:
        param_results['missing_status'].append(pid)
    else:
        param_results['by_status'][status] += 1

    # Units check (skip dimensionless)
    units = p.get('units', '').strip()
    name = p.get('name', pid).lower()
    is_dimensionless = any(x in name for x in ['alpha', 'ratio', 'mixing', 'angle', 'sin', 'cos', 'tan'])
    if not units and not is_dimensionless and value not in [0, 1, None]:
        param_results['missing_units'].append(pid)

    # Validation check
    has_validation = p.get('validation') is not None or p.get('experimentalBounds') is not None
    if has_validation:
        param_results['with_validation'] += 1
    else:
        param_results['missing_validation'].append(pid)
        if status == 'DERIVED':
            param_results['derived_without_validation'].append(pid)

    # Validation status check
    if p.get('experimentalBounds'):
        val_status = p.get('validationStatus', '').strip()
        if not val_status:
            param_results['validation_status_issues'].append({
                'id': pid,
                'issue': 'Has experimental bounds but no validationStatus'
            })

# Formula validation
formula_results = {
    'total': len(formulas),
    'with_derivation': 0,
    'missing_derivation': [],
    'missing_latex': [],
    'missing_category': [],
    'missing_input_params': [],
    'missing_output_params': [],
    'empty_input_params': [],
    'empty_output_params': [],
    'by_category': defaultdict(int)
}

for fid, f in formulas.items():
    if not isinstance(f, dict):
        continue

    # LaTeX check
    if not f.get('latex', '').strip():
        formula_results['missing_latex'].append(fid)

    # Category check
    cat = f.get('category', '').strip()
    if not cat:
        formula_results['missing_category'].append(fid)
    else:
        formula_results['by_category'][cat] += 1

    # Derivation check
    deriv = f.get('derivation')
    if deriv and deriv.get('steps'):
        formula_results['with_derivation'] += 1
    else:
        formula_results['missing_derivation'].append(fid)

    # Input/output params check
    inp = f.get('inputParams')
    out = f.get('outputParams')

    if inp is None:
        formula_results['missing_input_params'].append(fid)
    elif isinstance(inp, list) and len(inp) == 0:
        formula_results['empty_input_params'].append(fid)

    if out is None:
        formula_results['missing_output_params'].append(fid)
    elif isinstance(out, list) and len(out) == 0:
        formula_results['empty_output_params'].append(fid)

# Identify simulations needed
simulations_needed = defaultdict(list)
for pid in param_results['derived_without_validation']:
    p = params.get(pid, {})
    source = p.get('source', 'UNKNOWN')
    if source != 'UNKNOWN':
        simulations_needed[source].append(pid)

# Generate report
report = []
report.append('# Theory Output Validation Report')
report.append('')
report.append('**Generated:** 2025-12-28')
report.append('**Source File:** AutoGenerated/theory_output.json')
report.append('')
report.append('## Executive Summary')
report.append('')
report.append(f'- **Total Parameters:** {param_results["total"]}')
report.append(f'- **Parameters with Validation:** {param_results["with_validation"]} ({100*param_results["with_validation"]/param_results["total"]:.1f}%)')
report.append(f'- **Parameters Missing Validation:** {len(param_results["missing_validation"])} ({100*len(param_results["missing_validation"])/param_results["total"]:.1f}%)')
report.append('')
report.append(f'- **Total Formulas:** {formula_results["total"]}')
report.append(f'- **Formulas with Derivation:** {formula_results["with_derivation"]} ({100*formula_results["with_derivation"]/formula_results["total"]:.1f}%)')
report.append(f'- **Formulas Missing Derivation:** {len(formula_results["missing_derivation"])} ({100*len(formula_results["missing_derivation"])/formula_results["total"]:.1f}%)')
report.append('')

# Parameters section
report.append('## Parameter Validation')
report.append('')
report.append('### Parameters by Status')
report.append('')
for status, count in sorted(param_results['by_status'].items()):
    report.append(f'- **{status}:** {count}')
report.append('')

if param_results['invalid_value']:
    report.append('### Parameters with Invalid Values')
    report.append('')
    report.append(f'**Count:** {len(param_results["invalid_value"])}')
    report.append('')
    for pid in param_results['invalid_value']:
        p = params.get(pid, {})
        report.append(f'- `{pid}`: {p.get("name", "N/A")} = {p.get("value")}')
    report.append('')

if param_results['missing_source']:
    report.append('### Parameters Missing Source')
    report.append('')
    report.append(f'**Count:** {len(param_results["missing_source"])}')
    report.append('')
    for pid in param_results['missing_source']:
        report.append(f'- `{pid}`')
    report.append('')

if param_results['missing_units']:
    report.append('### Parameters Missing Units')
    report.append('')
    report.append(f'**Count:** {len(param_results["missing_units"])}')
    report.append('')
    for pid in param_results['missing_units']:
        p = params.get(pid, {})
        report.append(f'- `{pid}`: {p.get("name", "N/A")}')
    report.append('')

if param_results['derived_without_validation']:
    report.append('### Derived Parameters Without Validation')
    report.append('')
    report.append(f'**Count:** {len(param_results["derived_without_validation"])}')
    report.append('')
    report.append('These DERIVED parameters should have experimental validation data:')
    report.append('')
    for pid in param_results['derived_without_validation']:
        p = params.get(pid, {})
        report.append(f'- `{pid}`: {p.get("name", "N/A")} = {p.get("value")}')
    report.append('')

if param_results['validation_status_issues']:
    report.append('### Validation Status Issues')
    report.append('')
    report.append(f'**Count:** {len(param_results["validation_status_issues"])}')
    report.append('')
    for issue in param_results['validation_status_issues']:
        report.append(f'- `{issue["id"]}`: {issue["issue"]}')
    report.append('')

report.append('### All Parameters Missing Validation')
report.append('')
report.append(f'**Count:** {len(param_results["missing_validation"])}')
report.append('')
for pid in param_results['missing_validation']:
    p = params.get(pid, {})
    status = p.get('status', 'UNKNOWN')
    source = p.get('source', 'UNKNOWN')
    report.append(f'- `{pid}` ({status}, {source}): {p.get("name", "N/A")}')
report.append('')

# Simulations needed
if simulations_needed:
    report.append('## Simulations Responsible for Missing Validation')
    report.append('')
    report.append('The following simulations need to provide validation data for DERIVED parameters:')
    report.append('')
    for source, pids in sorted(simulations_needed.items()):
        report.append(f'### {source}')
        report.append('')
        report.append(f'**Parameters needing validation:** {len(pids)}')
        report.append('')
        for pid in pids:
            p = params.get(pid, {})
            report.append(f'- `{pid}`: {p.get("name", "N/A")} = {p.get("value")}')
        report.append('')

# Formulas section
report.append('## Formula Validation')
report.append('')
report.append('### Formulas by Category')
report.append('')
for cat, count in sorted(formula_results['by_category'].items()):
    report.append(f'- **{cat}:** {count}')
report.append('')

if formula_results['missing_derivation']:
    report.append('### Formulas Missing Derivation')
    report.append('')
    report.append(f'**Count:** {len(formula_results["missing_derivation"])}')
    report.append('')
    for fid in formula_results['missing_derivation']:
        f = formulas.get(fid, {})
        cat = f.get('category', 'UNKNOWN') if isinstance(f, dict) else 'UNKNOWN'
        report.append(f'- `{fid}` ({cat})')
    report.append('')

if formula_results['missing_input_params']:
    report.append('### Formulas Missing inputParams Field')
    report.append('')
    report.append(f'**Count:** {len(formula_results["missing_input_params"])}')
    report.append('')
    for fid in formula_results['missing_input_params']:
        report.append(f'- `{fid}`')
    report.append('')

if formula_results['empty_input_params']:
    report.append('### Formulas with Empty inputParams')
    report.append('')
    report.append(f'**Count:** {len(formula_results["empty_input_params"])}')
    report.append('')
    for fid in formula_results['empty_input_params']:
        report.append(f'- `{fid}`')
    report.append('')

if formula_results['missing_output_params']:
    report.append('### Formulas Missing outputParams Field')
    report.append('')
    report.append(f'**Count:** {len(formula_results["missing_output_params"])}')
    report.append('')
    for fid in formula_results['missing_output_params']:
        report.append(f'- `{fid}`')
    report.append('')

if formula_results['empty_output_params']:
    report.append('### Formulas with Empty outputParams')
    report.append('')
    report.append(f'**Count:** {len(formula_results["empty_output_params"])}')
    report.append('')
    for fid in formula_results['empty_output_params']:
        report.append(f'- `{fid}`')
    report.append('')

# Recommendations
report.append('## Recommendations')
report.append('')
recommendations = []

if param_results['invalid_value']:
    recommendations.append('1. **Fix Invalid Parameter Values:** Update parameters with null, NaN, or Inf values')

if param_results['derived_without_validation']:
    recommendations.append(f'{len(recommendations)+1}. **Add Validation for Derived Parameters:** Run simulations to generate experimental validation data for {len(param_results["derived_without_validation"])} DERIVED parameters')

if param_results['validation_status_issues']:
    recommendations.append(f'{len(recommendations)+1}. **Update Validation Status:** Set validationStatus (PASS/FAIL/MARGINAL) for parameters with experimental bounds')

if formula_results['missing_input_params'] or formula_results['missing_output_params']:
    recommendations.append(f'{len(recommendations)+1}. **Link Formula Parameters:** Add inputParams and outputParams fields to formulas')

if param_results['missing_units']:
    recommendations.append(f'{len(recommendations)+1}. **Add Units:** Specify units for {len(param_results["missing_units"])} dimensional parameters')

if not recommendations:
    recommendations.append('No critical issues found!')

for rec in recommendations:
    report.append(rec)

report.append('')
report.append('---')
report.append('')
report.append('*End of Report*')

# Save report
Path('reports').mkdir(exist_ok=True)
with open('reports/THEORY_OUTPUT_VALIDATION_REPORT.md', 'w', encoding='utf-8') as f:
    f.write('\n'.join(report))

print('Report saved to: reports/THEORY_OUTPUT_VALIDATION_REPORT.md')
print('')
print('='*60)
print('VALIDATION SUMMARY')
print('='*60)
print(f'\nPARAMETERS:')
print(f'  Total: {param_results["total"]}')
print(f'  With validation: {param_results["with_validation"]} ({100*param_results["with_validation"]/param_results["total"]:.1f}%)')
print(f'  Missing validation: {len(param_results["missing_validation"])}')
print(f'  Invalid values: {len(param_results["invalid_value"])}')
print(f'  Missing units: {len(param_results["missing_units"])}')
print(f'  Derived without validation: {len(param_results["derived_without_validation"])}')

print(f'\nFORMULAS:')
print(f'  Total: {formula_results["total"]}')
print(f'  With derivation: {formula_results["with_derivation"]} ({100*formula_results["with_derivation"]/formula_results["total"]:.1f}%)')
print(f'  Missing input/output params: {len(formula_results["missing_input_params"]) + len(formula_results["missing_output_params"])}')

if simulations_needed:
    print(f'\nSIMULATIONS NEEDED:')
    for source, pids in sorted(simulations_needed.items()):
        print(f'  {source}: {len(pids)} parameters')

print('\n' + '='*60)
