@echo off
REM Tolerance Sweep Launcher for Principia Metaphysica v24.1
REM ===========================================================
REM
REM Runs validation simulations with progressively tighter tolerances
REM until failure, identifying the current robustness level and
REM convergence toward exact precision.
REM
REM Usage:
REM   launch_tolerance_sweep.bat                    (run all simulations, all levels)
REM   launch_tolerance_sweep.bat adversarial        (run adversarial only)
REM   launch_tolerance_sweep.bat all standard,strict  (test standard and strict only)
REM
REM Philosophy:
REM   Zero-parameter theories claiming to describe reality exactly should
REM   approach zero deviation as:
REM   - Theory is refined (higher-order corrections)
REM   - Numerical precision increases
REM   - Experimental measurements improve
REM
REM Copyright (c) 2026 Andrew Keith Watts. All rights reserved.
REM

echo ======================================================================
echo  PRINCIPIA METAPHYSICA v24.1 - TOLERANCE SWEEP
echo ======================================================================
echo  Testing robustness from loose -^> tight tolerances until failure
echo  Levels: development -^> standard -^> strict -^> rigorous -^> exact
echo ======================================================================
echo.

REM Check if Python is available
python --version >nul 2>&1
if errorlevel 1 (
    echo ERROR: Python not found in PATH
    echo Please install Python 3.8+ or activate virtual environment
    pause
    exit /b 1
)

REM Set parameters
set SIMULATION=%1
set LEVELS=%2

if "%SIMULATION%"=="" set SIMULATION=all
if "%LEVELS%"=="" set LEVELS=all

echo Configuration:
echo   Simulation: %SIMULATION%
echo   Tolerance Levels: %LEVELS%
echo.
echo ======================================================================
echo.

REM Change to repository root
cd /d "%~dp0"

REM Run tolerance sweep
python simulations\PM\validation\tolerance_sweep.py --simulation %SIMULATION% --levels %LEVELS%

set EXITCODE=%ERRORLEVEL%

echo.
echo ======================================================================
if %EXITCODE%==0 (
    echo  TOLERANCE SWEEP COMPLETED SUCCESSFULLY
    echo  Check AutoGenerated\tolerance_sweep_report_v24.json for details
) else (
    echo  TOLERANCE SWEEP FAILED (exit code: %EXITCODE%^)
    echo  Check logs for errors
)
echo ======================================================================
echo.

REM Open results if successful
if %EXITCODE%==0 (
    if exist "AutoGenerated\tolerance_sweep_report_v24.json" (
        echo Opening results in default JSON viewer...
        start "" "AutoGenerated\tolerance_sweep_report_v24.json"
    )
)

pause
exit /b %EXITCODE%
