#!/usr/bin/env python3
"""
Test Visualization Generation
===============================

Quick test to verify all visualization generation functions work correctly.

Usage:
    python test_visualization_generation.py
"""

import sys
from pathlib import Path

# Add project root to path
PROJECT_ROOT = Path(__file__).parent
sys.path.insert(0, str(PROJECT_ROOT))

def test_visualizations():
    """Test all visualization generation functions."""
    print("=" * 80)
    print("TESTING VISUALIZATION GENERATION")
    print("=" * 80)

    errors = []

    # 1. Test Certificate Dashboards
    print("\n[TEST] Certificate Dashboards (v16.2)...")
    try:
        from simulations.visualizations.certificate_dashboard_v16_2 import (
            generate_dashboard, generate_gates_focus
        )
        result1 = generate_dashboard()
        result2 = generate_gates_focus()
        print(f"  [OK] Generated: {result1}")
        print(f"  [OK] Generated: {result2}")
    except Exception as e:
        errors.append(f"Certificate dashboards: {e}")
        print(f"  [FAIL] {e}")

    # 2. Test Four Pattern Orthogonality
    print("\n[TEST] Four Pattern Orthogonality (v16.2)...")
    try:
        from simulations.visualizations.four_pattern_orthogonality_v16_2 import (
            generate_four_pattern, generate_stability_view
        )
        result1 = generate_four_pattern()
        result2 = generate_stability_view()
        print(f"  [OK] Generated: {result1}")
        print(f"  [OK] Generated: {result2}")
    except Exception as e:
        errors.append(f"Four pattern: {e}")
        print(f"  [FAIL] {e}")

    # 3. Test Torsion Funnel
    print("\n[TEST] Torsion Funnel (v16.2)...")
    try:
        from simulations.visualizations.torsion_funnel_v16_2 import generate_torsion_funnel
        result = generate_torsion_funnel()
        print(f"  [OK] Generated: {result}")
    except Exception as e:
        errors.append(f"Torsion funnel: {e}")
        print(f"  [FAIL] {e}")

    # 4. Test Publication Figures
    print("\n[TEST] v24.1 Publication Figures...")
    try:
        # Check dependencies first
        params_file = PROJECT_ROOT / "AutoGenerated" / "parameters.json"
        stats_file = PROJECT_ROOT / "AutoGenerated" / "statistical_rigor_report_v24.json"

        if not params_file.exists():
            print(f"  [SKIP] Missing: {params_file}")
            errors.append("Publication figures: Missing parameters.json")
        elif not stats_file.exists():
            print(f"  [SKIP] Missing: {stats_file}")
            errors.append("Publication figures: Missing statistical_rigor_report_v24.json")
        else:
            sys.path.insert(0, str(PROJECT_ROOT / "scripts"))
            from generate_submission_figures import main as generate_figures
            generate_figures()
            print("  [OK] All publication figures generated")
    except Exception as e:
        errors.append(f"Publication figures: {e}")
        print(f"  [FAIL] {e}")

    # Summary
    print("\n" + "=" * 80)
    if errors:
        print(f"[RESULT] {len(errors)} ERRORS DETECTED:")
        for err in errors:
            print(f"  - {err}")
        return 1
    else:
        print("[RESULT] ALL VISUALIZATIONS GENERATED SUCCESSFULLY")
        return 0
    print("=" * 80)


if __name__ == "__main__":
    exit_code = test_visualizations()
    sys.exit(exit_code)
