#!/usr/bin/env python3
"""
Comprehensive test for references page fix
Tests file existence, JSON validity, structure, and provides test instructions
"""
import json
import sys
from pathlib import Path

# Fix Windows console encoding
if sys.platform == 'win32':
    import os
    os.system('chcp 65001 > nul 2>&1')
    if hasattr(sys.stdout, 'reconfigure'):
        sys.stdout.reconfigure(encoding='utf-8')

def test_file_existence():
    """Test 1: Check if references.json exists"""
    print("\n" + "="*60)
    print("TEST 1: File Existence")
    print("="*60)

    ref_path = Path("AutoGenerated/references.json")
    html_path = Path("Pages/references.html")

    if not ref_path.exists():
        print(f"❌ FAIL: {ref_path} does not exist!")
        return False
    print(f"✓ {ref_path} exists")

    if not html_path.exists():
        print(f"❌ FAIL: {html_path} does not exist!")
        return False
    print(f"✓ {html_path} exists")

    return True

def test_json_validity():
    """Test 2: Check if JSON is valid and properly encoded"""
    print("\n" + "="*60)
    print("TEST 2: JSON Validity and Encoding")
    print("="*60)

    ref_path = Path("AutoGenerated/references.json")

    try:
        with open(ref_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
        print("✓ JSON is valid and UTF-8 encoded")

        if not isinstance(data, dict):
            print(f"❌ FAIL: Expected object/dict, got {type(data)}")
            return False
        print(f"✓ Root is an object (dict)")

        return data
    except json.JSONDecodeError as e:
        print(f"❌ FAIL: Invalid JSON: {e}")
        return None
    except UnicodeDecodeError as e:
        print(f"❌ FAIL: Encoding error: {e}")
        return None
    except Exception as e:
        print(f"❌ FAIL: {e}")
        return None

def test_structure(data):
    """Test 3: Validate reference structure"""
    print("\n" + "="*60)
    print("TEST 3: Reference Structure")
    print("="*60)

    required_fields = ['id', 'authors', 'title', 'year', 'journal']
    errors = []

    ref_count = len(data)
    print(f"✓ Found {ref_count} references")

    # Check each reference
    for ref_id, ref in data.items():
        # Check ID match
        if ref.get('id') != ref_id:
            errors.append(f"ID mismatch in '{ref_id}'")

        # Check required fields
        for field in required_fields:
            if field not in ref:
                errors.append(f"Missing '{field}' in '{ref_id}'")

    if errors:
        print(f"❌ FAIL: Found {len(errors)} errors:")
        for error in errors[:5]:
            print(f"  - {error}")
        return False

    print(f"✓ All {ref_count} references have required fields")
    return True

def test_statistics(data):
    """Test 4: Calculate and display statistics"""
    print("\n" + "="*60)
    print("TEST 4: Statistics")
    print("="*60)

    total = len(data)
    with_arxiv = sum(1 for ref in data.values() if ref.get('arxiv'))
    with_doi = sum(1 for ref in data.values() if ref.get('doi'))
    with_citations = sum(1 for ref in data.values() if ref.get('citedByFormulas') or ref.get('citedByParams'))

    years = [ref['year'] for ref in data.values() if 'year' in ref]
    year_range = f"{min(years)} - {max(years)}" if years else "N/A"
    avg_year = sum(years) / len(years) if years else 0

    print(f"  Total references: {total}")
    print(f"  With arXiv: {with_arxiv} ({with_arxiv/total*100:.1f}%)")
    print(f"  With DOI: {with_doi} ({with_doi/total*100:.1f}%)")
    print(f"  With citations: {with_citations} ({with_citations/total*100:.1f}%)")
    print(f"  Year range: {year_range}")
    print(f"  Average year: {avg_year:.1f}")

    # Sample references
    print("\n  Sample references:")
    for ref_id, ref in list(data.items())[:3]:
        print(f"    - {ref.get('title', 'No title')[:60]}...")
        print(f"      {ref.get('authors', 'No authors')[:50]}... ({ref.get('year', 'N/A')})")

    return True

def test_html_paths():
    """Test 5: Check HTML file has correct paths"""
    print("\n" + "="*60)
    print("TEST 5: HTML Path Configuration")
    print("="*60)

    html_path = Path("Pages/references.html")

    try:
        with open(html_path, 'r', encoding='utf-8') as f:
            content = f.read()

        # Check for the correct path
        if '../AutoGenerated/references.json' in content:
            print("✓ Contains correct relative path: ../AutoGenerated/references.json")
        else:
            print("⚠ Warning: May not have correct relative path")

        # Check for Object.values (needed to convert object to array)
        if 'Object.values(data)' in content:
            print("✓ Contains Object.values() for object-to-array conversion")
        else:
            print("⚠ Warning: May not convert object to array correctly")

        return True
    except Exception as e:
        print(f"❌ FAIL: Could not read HTML file: {e}")
        return False

def print_test_instructions():
    """Print instructions for manual browser testing"""
    print("\n" + "="*60)
    print("MANUAL TESTING INSTRUCTIONS")
    print("="*60)
    print("""
To complete testing, follow these steps:

1. START WEB SERVER:
   Windows:   double-click start_server.bat
   Linux/Mac: ./start_server.sh
   Manual:    python -m http.server 8000

2. OPEN BROWSER:
   Navigate to: http://localhost:8000/Pages/references.html

3. CHECK LOADING:
   - Should see "Loading academic references..." briefly
   - Then display 34 references grouped by decade
   - No error messages

4. TEST FEATURES:
   - Search box: Type "Joyce" - should filter to Joyce papers
   - Filter buttons: Click "Sort by Year" - should reorder
   - Citation badges: Should show citation counts
   - Links: Click arXiv/DOI links - should open in new tab

5. CHECK CONSOLE (F12):
   Should see:
   [References] Successfully loaded from: ../AutoGenerated/references.json
   [References] Converted to array, length: 34
   [References] Successfully rendered references

6. EXPECTED DISPLAY:
   - Decade headers: 2020s, 2010s, 2000s, etc.
   - Each reference shows: title, authors, year, description
   - Citation badges with counts
   - Clickable arXiv/DOI links
   - Search and filter working smoothly
""")

def main():
    """Run all tests"""
    print("="*60)
    print("REFERENCES PAGE COMPREHENSIVE TEST")
    print("="*60)

    all_passed = True

    # Test 1: File existence
    if not test_file_existence():
        all_passed = False
        print("\n❌ CRITICAL: Files missing. Cannot continue.")
        sys.exit(1)

    # Test 2: JSON validity
    data = test_json_validity()
    if not data:
        all_passed = False
        print("\n❌ CRITICAL: JSON invalid. Cannot continue.")
        sys.exit(1)

    # Test 3: Structure
    if not test_structure(data):
        all_passed = False

    # Test 4: Statistics
    test_statistics(data)

    # Test 5: HTML paths
    if not test_html_paths():
        all_passed = False

    # Print manual test instructions
    print_test_instructions()

    # Final result
    print("="*60)
    if all_passed:
        print("✅ ALL AUTOMATED TESTS PASSED")
        print("="*60)
        print("\nNext step: Complete manual browser testing (see instructions above)")
        return 0
    else:
        print("❌ SOME TESTS FAILED")
        print("="*60)
        print("\nPlease fix the errors above before browser testing")
        return 1

if __name__ == '__main__':
    sys.exit(main())
