#!/usr/bin/env python3
"""
Validate all parameter and formula references in sections.json
"""
import json
import re
from pathlib import Path

def load_json(filepath):
    """Load JSON file with UTF-8 encoding"""
    with open(filepath, 'r', encoding='utf-8') as f:
        return json.load(f)

def extract_param_refs(content):
    """Extract all data-param-id references from HTML content"""
    if not content:
        return []
    pattern = r'data-param-id=["\']([^"\']+)["\']'
    return re.findall(pattern, str(content))

def extract_formula_refs(content):
    """Extract all data-formula-id references from HTML content"""
    if not content:
        return []
    pattern = r'data-formula-id=["\']([^"\']+)["\']'
    return re.findall(pattern, str(content))

def check_latex_balance(latex_str):
    """Check if LaTeX braces are balanced"""
    if not latex_str:
        return True, ""

    # Count braces
    open_count = latex_str.count('{')
    close_count = latex_str.count('}')

    if open_count != close_count:
        return False, f"Unbalanced braces: {open_count} open, {close_count} close"

    # Check for common LaTeX errors
    errors = []
    if '\\\\' in latex_str and '\\\\\\\\' not in latex_str:
        # This is usually fine, just a line break
        pass

    if latex_str.count('$') % 2 != 0:
        errors.append("Unmatched $ delimiter")

    return len(errors) == 0, "; ".join(errors) if errors else ""

def main():
    base_path = Path(__file__).parent / 'AutoGenerated'

    # Load all data files
    print("Loading data files...")
    sections_data = load_json(base_path / 'sections.json')
    formulas_data = load_json(base_path / 'formulas.json')

    # Load parameters from theory_output.json
    try:
        theory_data = load_json(base_path / 'theory_output.json')
        parameters = theory_data.get('parameters', {})
    except Exception as e:
        print(f"Warning: Could not load theory_output.json: {e}")
        print("Will only validate formula references.")
        parameters = {}

    # Get all valid formula IDs
    formula_ids = set(formulas_data.get('formulas', {}).keys())
    print(f"\nFound {len(formula_ids)} formulas")

    # Get all valid parameter IDs
    param_ids = set(parameters.keys()) if parameters else set()
    print(f"Found {len(param_ids)} parameters")

    # Validate sections
    sections = sections_data.get('sections', {})
    print(f"Found {len(sections)} sections\n")

    # Track issues
    param_ref_issues = []
    formula_ref_issues = []
    latex_issues = []

    # Check each section
    for section_id, section in sections.items():
        section_title = section.get('title', section_id)

        # Check content blocks
        for block in section.get('contentBlocks', []):
            content = str(block.get('content', ''))

            # Check parameter references
            param_refs = extract_param_refs(content)
            for ref in param_refs:
                if param_ids and ref not in param_ids:
                    param_ref_issues.append({
                        'section': section_id,
                        'title': section_title,
                        'ref': ref,
                        'type': 'parameter'
                    })

            # Check formula references
            formula_refs = extract_formula_refs(content)
            for ref in formula_refs:
                if ref not in formula_ids:
                    formula_ref_issues.append({
                        'section': section_id,
                        'title': section_title,
                        'ref': ref,
                        'type': 'formula'
                    })

    # Check LaTeX in formulas
    for formula_id, formula_data in formulas_data.get('formulas', {}).items():
        latex = formula_data.get('latex', '')
        is_valid, error_msg = check_latex_balance(latex)
        if not is_valid:
            latex_issues.append({
                'formula_id': formula_id,
                'label': formula_data.get('label', ''),
                'error': error_msg,
                'latex': latex[:100] + '...' if len(latex) > 100 else latex
            })

    # Report results
    print("="*70)
    print("VALIDATION RESULTS")
    print("="*70)

    if param_ref_issues:
        print(f"\n[!] INVALID PARAMETER REFERENCES: {len(param_ref_issues)}")
        for issue in param_ref_issues[:10]:
            print(f"  Section {issue['section']} ({issue['title']}): {issue['ref']}")
        if len(param_ref_issues) > 10:
            print(f"  ... and {len(param_ref_issues) - 10} more")
    else:
        print("\n[OK] All parameter references are valid")

    if formula_ref_issues:
        print(f"\n[!] INVALID FORMULA REFERENCES: {len(formula_ref_issues)}")
        for issue in formula_ref_issues[:10]:
            print(f"  Section {issue['section']} ({issue['title']}): {issue['ref']}")
        if len(formula_ref_issues) > 10:
            print(f"  ... and {len(formula_ref_issues) - 10} more")
    else:
        print("\n[OK] All formula references are valid")

    if latex_issues:
        print(f"\n[!] LATEX SYNTAX ISSUES: {len(latex_issues)}")
        for issue in latex_issues[:5]:
            print(f"  {issue['formula_id']} {issue['label']}: {issue['error']}")
            print(f"    {issue['latex']}")
        if len(latex_issues) > 5:
            print(f"  ... and {len(latex_issues) - 5} more")
    else:
        print("\n[OK] All LaTeX syntax appears valid")

    # Summary
    total_issues = len(param_ref_issues) + len(formula_ref_issues) + len(latex_issues)
    print("\n" + "="*70)
    if total_issues == 0:
        print("[OK] NO ISSUES FOUND - Paper is ready for publication!")
    else:
        print(f"[!] TOTAL ISSUES: {total_issues}")
        print("  Please review and fix the issues listed above.")
    print("="*70)

    return total_issues == 0

if __name__ == '__main__':
    success = main()
    exit(0 if success else 1)
