#!/usr/bin/env python3
"""
Validate references.json structure and content
"""
import json
import sys
from pathlib import Path

# Fix Windows console encoding
if sys.platform == 'win32':
    import os
    os.system('chcp 65001 > nul 2>&1')
    if hasattr(sys.stdout, 'reconfigure'):
        sys.stdout.reconfigure(encoding='utf-8')

def validate_references():
    """Validate the references.json file"""

    ref_path = Path("AutoGenerated/references.json")

    if not ref_path.exists():
        print(f"ERROR: {ref_path} does not exist!")
        return False

    print(f"✓ Found {ref_path}")

    # Load and parse JSON
    try:
        with open(ref_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
    except json.JSONDecodeError as e:
        print(f"ERROR: Failed to parse JSON: {e}")
        return False
    except Exception as e:
        print(f"ERROR: Failed to read file: {e}")
        return False

    print(f"✓ Successfully parsed JSON")

    # Check structure
    if not isinstance(data, dict):
        print(f"ERROR: Expected object/dict at root, got {type(data)}")
        return False

    print(f"✓ Root is an object (dict)")

    ref_count = len(data)
    print(f"✓ Found {ref_count} references")

    # Validate each reference
    required_fields = ['id', 'authors', 'title', 'year', 'journal']
    optional_fields = ['arxiv', 'doi', 'description', 'citedByFormulas', 'citedByParams']

    errors = []
    warnings = []

    for ref_id, ref in data.items():
        # Check that ref_id matches the id field
        if ref.get('id') != ref_id:
            errors.append(f"Reference '{ref_id}': ID mismatch (id field is '{ref.get('id')}')")

        # Check required fields
        for field in required_fields:
            if field not in ref:
                errors.append(f"Reference '{ref_id}': Missing required field '{field}'")

        # Check year is a number
        if 'year' in ref and not isinstance(ref['year'], int):
            errors.append(f"Reference '{ref_id}': year must be an integer, got {type(ref['year'])}")

        # Check citedByFormulas and citedByParams are arrays if present
        if 'citedByFormulas' in ref and not isinstance(ref['citedByFormulas'], list):
            errors.append(f"Reference '{ref_id}': citedByFormulas must be an array")

        if 'citedByParams' in ref and not isinstance(ref['citedByParams'], list):
            errors.append(f"Reference '{ref_id}': citedByParams must be an array")

        # Warnings for missing optional but useful fields
        if not ref.get('arxiv') and not ref.get('doi'):
            warnings.append(f"Reference '{ref_id}': No arXiv or DOI link")

    # Report results
    if errors:
        print(f"\n❌ Found {len(errors)} errors:")
        for error in errors[:10]:  # Show first 10
            print(f"  - {error}")
        if len(errors) > 10:
            print(f"  ... and {len(errors) - 10} more")
        return False

    print(f"✓ All references have required fields")

    if warnings:
        print(f"\n⚠ Found {len(warnings)} warnings:")
        for warning in warnings[:5]:  # Show first 5
            print(f"  - {warning}")
        if len(warnings) > 5:
            print(f"  ... and {len(warnings) - 5} more")

    # Summary statistics
    print(f"\n📊 Statistics:")
    with_arxiv = sum(1 for ref in data.values() if ref.get('arxiv'))
    with_doi = sum(1 for ref in data.values() if ref.get('doi'))
    with_citations = sum(1 for ref in data.values() if ref.get('citedByFormulas') or ref.get('citedByParams'))

    print(f"  - Total references: {ref_count}")
    print(f"  - With arXiv: {with_arxiv} ({with_arxiv/ref_count*100:.1f}%)")
    print(f"  - With DOI: {with_doi} ({with_doi/ref_count*100:.1f}%)")
    print(f"  - With citations: {with_citations} ({with_citations/ref_count*100:.1f}%)")

    # Year distribution
    years = [ref['year'] for ref in data.values() if 'year' in ref]
    if years:
        print(f"  - Year range: {min(years)} - {max(years)}")
        print(f"  - Average year: {sum(years) / len(years):.1f}")

    print(f"\n✅ Validation passed!")
    return True

if __name__ == '__main__':
    success = validate_references()
    sys.exit(0 if success else 1)
