#!/usr/bin/env python3
"""
S8 Simulation Verification Script
===================================

Quickly verify that the S8 tension simulation is properly integrated
and producing correct results.

Run with: python verify_s8_simulation.py
"""

import json
import sys
from pathlib import Path

def verify_s8_integration():
    """Verify S8 simulation integration."""

    print("\n" + "="*80)
    print(" S8 SIMULATION VERIFICATION")
    print("="*80)

    # Check file exists
    sim_file = Path("simulations/v16/cosmology/s8_suppression_v16_1.py")
    if not sim_file.exists():
        print(f"\n[FAIL] Simulation file not found: {sim_file}")
        return False
    print(f"\n[OK] Simulation file exists: {sim_file}")

    # Check theory_output.json exists
    output_file = Path("AutoGenerated/theory_output.json")
    if not output_file.exists():
        print(f"[FAIL] Output file not found: {output_file}")
        print("Run: python run_all_simulations.py")
        return False
    print(f"[OK] Output file exists: {output_file}")

    # Load and check parameters
    try:
        with open(output_file, 'r', encoding='utf-8') as f:
            data = json.load(f)
    except Exception as e:
        print(f"[FAIL] Could not load output file: {e}")
        return False

    # Check S8 parameters
    expected_params = [
        'planck.S8',
        'desi.sigma8',
        'cosmology.s8_pm_predicted',
        'cosmology.s8_suppression_factor',
        'cosmology.growth_index_pm',
        'cosmology.s8_tension_kids',
        'cosmology.s8_tension_des',
        'cosmology.s8_tension_planck',
    ]

    print("\n[PARAMETERS] Checking S8-related parameters:")
    params = data.get('parameters', {})
    missing = []
    for param in expected_params:
        if param in params:
            value = params[param].get('value', 'N/A')
            source = params[param].get('source', 'N/A')
            print(f"  [OK] {param}: {value} (from {source})")
        else:
            print(f"  [MISS] {param}")
            missing.append(param)

    if missing:
        print(f"\n[FAIL] Missing parameters: {missing}")
        return False

    # Check formulas
    expected_formulas = [
        's8-definition',
        'growth-rate-equation',
        'pm-dark-energy-density',
        'growth-suppression-factor',
        's8-prediction-pm',
    ]

    print("\n[FORMULAS] Checking S8-related formulas:")
    formulas = data.get('formulas', {})
    missing_formulas = []
    for formula_id in expected_formulas:
        if formula_id in formulas:
            label = formulas[formula_id].get('label', 'N/A')
            category = formulas[formula_id].get('category', 'N/A')
            print(f"  [OK] {formula_id}: {label} ({category})")
        else:
            print(f"  [MISS] {formula_id}")
            missing_formulas.append(formula_id)

    if missing_formulas:
        print(f"\n[FAIL] Missing formulas: {missing_formulas}")
        return False

    # Check section content
    print("\n[SECTIONS] Checking section content:")
    sections = data.get('sections', {})
    if '5.4' in sections:
        section = sections['5.4']
        print(f"  [OK] Section 5.4: {section.get('title', 'N/A')}")
        print(f"       Content blocks: {len(section.get('contentBlocks', []))}")
        print(f"       Formula refs: {len(section.get('formulaRefs', []))}")
    else:
        print("  [WARN] Section 5.4 not found (may be combined with Section 5)")

    # Validate physics
    print("\n[PHYSICS] Validating physical results:")
    s8_pm = params.get('cosmology.s8_pm_predicted', {}).get('value', 0)
    s8_planck = params.get('planck.S8', {}).get('value', 0)
    suppression = params.get('cosmology.s8_suppression_factor', {}).get('value', 0)

    print(f"  PM S8 prediction: {s8_pm:.4f}")
    print(f"  Planck S8: {s8_planck:.3f}")
    print(f"  Growth suppression beta: {suppression:.4f}")

    # Sanity checks
    checks_passed = True
    if not (0.8 < s8_pm < 0.85):
        print(f"  [WARN] S8_PM outside expected range [0.8, 0.85]: {s8_pm}")
        checks_passed = False
    if not (0.99 < suppression < 1.01):
        print(f"  [WARN] Suppression factor outside expected range [0.99, 1.01]: {suppression}")
        checks_passed = False

    if checks_passed:
        print("  [OK] Physical values in expected ranges")

    # Compare to DESI
    sigma8_desi = params.get('desi.sigma8', {}).get('value', 0)
    omega_m = params.get('desi.Omega_m', {}).get('value', 0.3)
    s8_from_desi = sigma8_desi * (omega_m / 0.3)**0.5

    print(f"\n[COMPARISON] DESI-based calculation:")
    print(f"  sigma8 (DESI): {sigma8_desi:.3f}")
    print(f"  Omega_m (DESI): {omega_m:.4f}")
    print(f"  S8 = sigma8 * sqrt(Omega_m/0.3): {s8_from_desi:.4f}")
    print(f"  PM S8 (with suppression): {s8_pm:.4f}")
    print(f"  Difference: {abs(s8_pm - s8_from_desi):.4f} ({100*abs(s8_pm - s8_from_desi)/s8_from_desi:.2f}%)")

    # Final summary
    print("\n" + "="*80)
    print(" VERIFICATION SUMMARY")
    print("="*80)
    print(f"  File: {sim_file} - OK")
    print(f"  Parameters: {len(expected_params)} found - OK")
    print(f"  Formulas: {len(expected_formulas)} found - OK")
    print(f"  Physics: Values in expected ranges - OK")
    print("\n[SUCCESS] S8 simulation is properly integrated!")
    print("="*80)

    return True


if __name__ == "__main__":
    success = verify_s8_integration()
    sys.exit(0 if success else 1)
