#!/usr/bin/env python3
"""
Visualize validation issues in a more readable format.
Shows the dependency graph of missing parameters.
"""

import json
from pathlib import Path
from collections import defaultdict

def load_theory_output():
    """Load the theory_output.json file."""
    file_path = Path(__file__).parent / 'AutoGenerated' / 'theory_output.json'
    with open(file_path, 'r', encoding='utf-8') as f:
        return json.load(f)

def analyze_formula_dependencies():
    """Analyze which formulas are blocked by missing parameters."""
    data = load_theory_output()

    # Get all existing parameters
    existing_params = set(data.get('parameters', {}).keys())

    # Get all formulas
    formulas = data.get('formulas', {})

    # Analyze each formula
    blocked_formulas = defaultdict(lambda: {'missing_inputs': [], 'missing_outputs': []})

    for formula_id, formula_data in formulas.items():
        # Check input parameters
        for param in formula_data.get('input_params', []):
            if param and param not in existing_params:
                blocked_formulas[formula_id]['missing_inputs'].append(param)

        # Check output parameters
        for param in formula_data.get('output_params', []):
            if param and param not in existing_params:
                blocked_formulas[formula_id]['missing_outputs'].append(param)

    # Remove formulas with no missing params
    blocked_formulas = {k: v for k, v in blocked_formulas.items()
                       if v['missing_inputs'] or v['missing_outputs']}

    return blocked_formulas, formulas

def print_formula_blocks():
    """Print formulas that are blocked by missing parameters."""
    blocked, all_formulas = analyze_formula_dependencies()

    print("=" * 80)
    print("FORMULA DEPENDENCY ANALYSIS")
    print("=" * 80)
    print()

    if not blocked:
        print("All formulas have their required parameters!")
        return

    print(f"Total formulas blocked: {len(blocked)}")
    print()

    # Categorize by severity
    critical = {}  # Missing inputs (can't compute)
    incomplete = {}  # Missing outputs (computed but not stored)
    both = {}  # Missing both

    for fid, info in blocked.items():
        if info['missing_inputs'] and info['missing_outputs']:
            both[fid] = info
        elif info['missing_inputs']:
            critical[fid] = info
        else:
            incomplete[fid] = info

    # Print critical (missing inputs)
    if critical or both:
        print("CRITICAL - Formulas that cannot compute (missing inputs):")
        print("-" * 80)
        for fid in sorted(list(critical.keys()) + list(both.keys())):
            info = blocked[fid]
            formula = all_formulas[fid]
            print(f"\n{fid}:")
            print(f"  Label: {formula.get('label', 'N/A')}")
            print(f"  Category: {formula.get('category', 'N/A')}")
            if info['missing_inputs']:
                print(f"  Missing inputs ({len(info['missing_inputs'])}):")
                for param in info['missing_inputs']:
                    print(f"    - {param}")
            if info['missing_outputs']:
                print(f"  Missing outputs ({len(info['missing_outputs'])}):")
                for param in info['missing_outputs']:
                    print(f"    - {param}")
        print()

    # Print incomplete (missing outputs only)
    if incomplete:
        print("INCOMPLETE - Formulas that compute but results not stored:")
        print("-" * 80)
        for fid in sorted(incomplete.keys()):
            info = incomplete[fid]
            formula = all_formulas[fid]
            print(f"\n{fid}:")
            print(f"  Label: {formula.get('label', 'N/A')}")
            print(f"  Missing outputs ({len(info['missing_outputs'])}):")
            for param in info['missing_outputs']:
                print(f"    - {param}")
        print()

    # Summary
    print("=" * 80)
    print("SUMMARY")
    print("=" * 80)
    print(f"Total blocked formulas: {len(blocked)}")
    print(f"  - Critical (missing inputs): {len(critical) + len(both)}")
    print(f"  - Incomplete (missing outputs only): {len(incomplete)}")
    print()

    # Count unique missing params
    all_missing = set()
    for info in blocked.values():
        all_missing.update(info['missing_inputs'])
        all_missing.update(info['missing_outputs'])

    print(f"Unique missing parameters: {len(all_missing)}")
    print()

    # Group by category
    categories = defaultdict(set)
    for param in all_missing:
        prefix = param.split('.')[0] if '.' in param else 'other'
        categories[prefix].add(param)

    print("Missing parameters by category:")
    for category, params in sorted(categories.items(), key=lambda x: -len(x[1])):
        print(f"  {category}: {len(params)} parameters")

def main():
    print_formula_blocks()

if __name__ == '__main__':
    main()
