"""
generate_eml_trees.py — Pre-generate EML operator-tree JSON for all formulas.

Reads AutoGenerated/formulas.json, calls parse_eml_tree() on each formula
that has eml_tree_str or eml_description, and writes the resulting tree
dicts to AutoGenerated/eml_trees.json keyed by formula ID.

Usage:
    python scripts/generation/generate_eml_trees.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(ROOT))

try:
    from eml_math.tree import parse_eml_tree
    from eml_math.evaluator import ParseError
except ImportError as e:
    print(f"ERROR: {e}")
    print("Install: pip install -e H:/Github/EML-Math")
    sys.exit(1)

FORMULAS_JSON = ROOT / "AutoGenerated" / "formulas.json"
OUTPUT_JSON   = ROOT / "AutoGenerated" / "eml_trees.json"


def _get_expr(formula: dict) -> str | None:
    """Return the best available expression string for a formula."""
    ts = formula.get("eml_tree_str", "")
    if ts:
        return f"EML: {ts}"
    ed = formula.get("eml_description", "")
    if ed and ed.startswith("EML:"):
        return ed
    return None


def main() -> None:
    with open(FORMULAS_JSON, encoding="utf-8") as f:
        data = json.load(f)

    formulas: dict = data.get("formulas", data)

    entries: dict = {}
    n_ok = n_err = n_skip = 0

    for fid, formula in formulas.items():
        expr = _get_expr(formula)
        if not expr:
            n_skip += 1
            continue
        try:
            # pure-eml tree (binary eml(L, R) primitive throughout) for the SVG renderer
            pure_tree = parse_eml_tree(expr, pure_eml=True)
            # compact-mode tree → drives LaTeX rendering (preserves operator labels)
            compact_tree = parse_eml_tree(expr, expand_eml=False)
            entries[fid] = {
                "tree":  pure_tree.to_dict(),
                "latex": compact_tree.to_latex(),
            }
            n_ok += 1
        except (ParseError, Exception) as exc:
            entries[fid] = {
                "tree":  {"label": f"<error: {exc}>", "kind": "unknown"},
                "latex": "",
            }
            n_err += 1

    with open(OUTPUT_JSON, "w", encoding="utf-8") as f:
        json.dump(entries, f, ensure_ascii=False, indent=2)

    print(f"EML tree generation complete:")
    print(f"  Parsed:  {n_ok}")
    print(f"  Errors:  {n_err}")
    print(f"  Skipped: {n_skip}")
    print(f"  Output:  {OUTPUT_JSON}")


if __name__ == "__main__":
    main()
