#!/usr/bin/env python3
"""
Migrate Section 1 (Introduction) content to theory_output.json
Extracts content from git history and structures it for the JSON format.
"""

import json
import subprocess
import re
from bs4 import BeautifulSoup
from pathlib import Path

def get_git_file_content(commit, filepath):
    """Get file content from a specific git commit."""
    try:
        result = subprocess.run(
            ['git', 'show', f'{commit}:{filepath}'],
            capture_output=True,
            text=True,
            encoding='utf-8',
            check=True,
            cwd=r'h:\Github\PrincipiaMetaphysica'
        )
        return result.stdout
    except subprocess.CalledProcessError as e:
        print(f"Error retrieving file from git: {e}")
        return None

def extract_section_content(html_content):
    """Extract text content, formulas, and structure from HTML."""
    soup = BeautifulSoup(html_content, 'html.parser')

    content_blocks = []

    # Find the main content area
    main_content = soup.find('main') or soup.find('body')
    if not main_content:
        print("Warning: Could not find main content area")
        return content_blocks

    # Extract section title and abstract from hero section
    hero = main_content.find(class_='section-hero')
    title = None
    abstract = None

    if hero:
        h1 = hero.find('h1')
        if h1:
            title = h1.get_text(strip=True)
        lead = hero.find(class_='lead')
        if lead:
            abstract = lead.get_text(strip=True)

    # Process subsections
    subsections = main_content.find_all(class_='subsection')

    for subsection in subsections:
        # Get subsection title
        h2 = subsection.find('h2')
        if h2:
            subsection_title = h2.get_text(strip=True)
            content_blocks.append({
                "type": "heading",
                "level": 2,
                "content": subsection_title,
                "formula_id": None,
                "label": None
            })

        # Process paragraphs and equations
        for elem in subsection.find_all(['p', 'div'], recursive=False):
            if 'equation-box' in elem.get('class', []):
                # Extract equation
                equation_content = elem.get_text(strip=True)
                # Try to find LaTeX if present
                latex_content = equation_content

                content_blocks.append({
                    "type": "formula",
                    "content": latex_content,
                    "formula_id": None,
                    "label": None
                })
            elif elem.name == 'p':
                para_text = elem.get_text(strip=True)
                if para_text:
                    content_blocks.append({
                        "type": "paragraph",
                        "content": para_text,
                        "formula_id": None,
                        "label": None
                    })

    return {
        "title": title or "Introduction",
        "abstract": abstract or "An introduction to the Principia Metaphysica framework.",
        "content_blocks": content_blocks
    }

def create_section_1_entry():
    """Create Section 1 entry for theory_output.json."""

    # Get the old introduction.html from git
    print("Extracting introduction.html from git history (commit 6b56d9c)...")
    html_content = get_git_file_content('6b56d9c', 'sections/introduction.html')

    if not html_content:
        print("Failed to retrieve introduction.html from git")
        return None

    print(f"Retrieved {len(html_content)} characters of HTML content")

    # Extract structured content
    print("Parsing HTML and extracting content...")
    section_data = extract_section_content(html_content)

    print(f"Extracted {len(section_data['content_blocks'])} content blocks")
    print(f"Title: {section_data['title']}")
    print(f"Abstract: {section_data['abstract'][:100]}..." if len(section_data['abstract']) > 100 else section_data['abstract'])

    # Create section 1 structure
    section_1 = {
        "section_id": "1",
        "subsection_id": None,
        "title": section_data['title'],
        "abstract": section_data['abstract'],
        "content_blocks": section_data['content_blocks']
    }

    return section_1

def update_theory_output_json(section_1):
    """Add section 1 to theory_output.json."""

    json_path = Path(r'h:\Github\PrincipiaMetaphysica\AutoGenerated\theory_output.json')

    print(f"\nReading theory_output.json from {json_path}...")

    # Read existing JSON
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    # Check if sections key exists
    if 'sections' not in data:
        data['sections'] = {}

    # Add section 1
    data['sections']['1'] = section_1

    # Sort sections (1, 2, 3, 4, 5, ...)
    sorted_sections = {}
    def sort_key(x):
        if x.isdigit():
            return (0, int(x))  # Numbers first, sorted numerically
        elif len(x) == 1 and x.isalpha():
            return (1, ord(x))  # Single letters (appendices) second
        else:
            return (2, x)  # Other keys last, sorted alphabetically

    for key in sorted(data['sections'].keys(), key=sort_key):
        sorted_sections[key] = data['sections'][key]
    data['sections'] = sorted_sections

    # Update metadata
    if 'metadata' in data:
        from datetime import datetime
        data['metadata']['timestamp'] = datetime.now().isoformat()
        # Increment version
        if 'version' in data['metadata']:
            current_version = float(data['metadata']['version'])
            data['metadata']['version'] = str(current_version + 0.1)

    print(f"\nWriting updated theory_output.json...")

    # Write back to JSON
    with open(json_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

    print(f"[OK] Successfully added section 1 to theory_output.json")
    print(f"  Total sections: {len(data['sections'])}")
    print(f"  Section IDs: {list(data['sections'].keys())}")

def main():
    """Main migration process."""
    print("="*60)
    print("SECTION 1 (INTRODUCTION) MIGRATION")
    print("="*60)

    # Step 1: Create section 1 entry
    section_1 = create_section_1_entry()

    if not section_1:
        print("\n[ERROR] Failed to create section 1 entry")
        return

    # Step 2: Update theory_output.json
    update_theory_output_json(section_1)

    print("\n" + "="*60)
    print("MIGRATION COMPLETE")
    print("="*60)
    print("\nNext steps:")
    print("1. Review section 1 in theory_output.json")
    print("2. Test sections.html#1 to verify content renders correctly")
    print("3. Delete sections/introduction.html redirect file (it's now obsolete)")

if __name__ == "__main__":
    main()
