"""
Migrate higher-dimensional geometry foundations from HTML to JSON.
Handles: kaluza-klein.html, g2-manifolds.html, calabi-yau.html
"""

import json
import os
import re

# Read existing foundations_data.json
foundations_json_path = r"h:\Github\PrincipiaMetaphysica\AutoGenerated\foundations_data.json"
with open(foundations_json_path, 'r', encoding='utf-8') as f:
    foundations_data = json.load(f)

# Define the new entries for higher-dimensional geometry
geometry_foundations = {
    "kaluza-klein": {
        "id": "kaluza-klein",
        "title": "Kaluza-Klein Theory",
        "year": 1921,
        "equation": "Higher D → 4D | Compactification on S¹",
        "summary": "The groundbreaking theory showing how extra spatial dimensions can be 'curled up' so small they become invisible, unifying gravity and electromagnetism in higher dimensions.",
        "badge": "established",
        "description": "Extra dimensions can be compactified (curled up) to such small sizes that they're invisible at low energies. Motion in the compact dimension appears as massive particles in 4D. The mass spectrum: m_n = n/R, where R is the compactification radius.",
        "key_concepts": [
            {
                "title": "Compactification",
                "content": "Just like a garden hose looks 1D from far away but is really 2D (with a tiny circular dimension), our universe might have extra dimensions curled up at the Planck scale (~10^-35 m)."
            },
            {
                "title": "KK Tower",
                "content": "Motion in the compact dimension appears as massive particles in 4D. The mass spectrum: m_n = n/R, where R is the compactification radius and n = 0, 1, 2, ..."
            },
            {
                "title": "Zero Mode",
                "content": "The n=0 mode is massless and corresponds to the 4D fields we observe (photon, graviton). Heavy modes (n≥1) are too massive to produce at current energies."
            }
        ],
        "formulas": [
            {
                "name": "5D Metric",
                "equation": "ds²_(5D) = g_μν dx^μ dx^ν + φ²(dy + A_μ dx^μ)²",
                "components": [
                    {
                        "symbol": "g_μν",
                        "name": "4D Metric Tensor",
                        "description": "The effective 4D spacetime metric after compactification"
                    },
                    {
                        "symbol": "A_μ",
                        "name": "KK Vector (Gauge Field)",
                        "description": "The 4D electromagnetic potential arising from the 5th dimension"
                    },
                    {
                        "symbol": "φ",
                        "name": "Radion (Dilaton)",
                        "description": "The scalar field describing fluctuations in the size of the compact dimension"
                    }
                ]
            },
            {
                "name": "KK Mass Spectrum",
                "equation": "m²_n = (n/R)²",
                "description": "Tower of massive states from momentum in the compact dimension. n=0: massless (our observed particles), n≥1: massive KK modes (not yet observed)"
            }
        ],
        "pm_applications": [
            "26D → 13D → 6D → 4D reduction pathway",
            "Multiple compactification scales",
            "Flux compactification & moduli stabilization"
        ],
        "references": [
            {
                "title": "Kaluza-Klein Theory in Perspective",
                "author": "Duff, M. J.",
                "year": 1994,
                "link": "https://arxiv.org/abs/hep-th/9410046"
            },
            {
                "title": "Wikipedia: Kaluza-Klein Theory",
                "link": "https://en.wikipedia.org/wiki/Kaluza%E2%80%93Klein_theory"
            }
        ]
    },
    "g2-manifolds": {
        "id": "g2-manifolds",
        "title": "G₂ Manifolds",
        "year": 1987,
        "equation": "dφ = 0, d(*φ) = 0",
        "summary": "Seven-dimensional Riemannian manifolds with holonomy group G₂, used for M-theory compactifications in the 13D shadow.",
        "badge": "established",
        "description": "G₂ manifolds are exceptional 7-dimensional Riemannian manifolds with holonomy group G₂, the smallest of the five exceptional Lie groups. In PM's 2T physics framework, the 13D shadow compactifies on a 7D G₂ manifold, yielding the dimensional structure 13D → 6D bulk.",
        "key_properties": [
            {
                "property": "Dimension",
                "value": "7 (real dimension)"
            },
            {
                "property": "Holonomy Group",
                "value": "G₂ ⊂ SO(7)"
            },
            {
                "property": "Parallel Spinors",
                "value": "1 real spinor (8 components)"
            },
            {
                "property": "Ricci Curvature",
                "value": "Ricci-flat (Ric = 0)"
            },
            {
                "property": "Supersymmetry",
                "value": "N=1 in 4D (M-theory)"
            }
        ],
        "flux_topology": {
            "bare_chi": 0,
            "flux_dressed_chi": 72,
            "chi_eff_total": 144,
            "n_gen": 3,
            "description": "The distinction between χ=0 (bare) and χ_eff=72 (flux-dressed) is crucial. G₄ flux quantization modifies the effective topology via backreaction."
        },
        "tcs_construction": {
            "method": "Twisted Connected Sum (TCS)",
            "gluing_angle": "θ = π/6 (30 degrees)",
            "b2": 4,
            "b3": 24,
            "chi_eff": 144,
            "nu": 24,
            "description": "PM uses a specific TCS construction with precise topological invariants"
        },
        "pm_applications": [
            "13D → 6D compactification in 2T framework",
            "SO(10) gauge enhancement from D₅ singularities",
            "Flux-dressed topology yields 3 generations",
            "GUT scale M_GUT = 2.118×10¹⁶ GeV from torsion topology"
        ],
        "references": [
            {
                "title": "Compact Manifolds with Special Holonomy",
                "author": "Joyce, D.",
                "year": 2000
            },
            {
                "title": "Twisted connected sums and special Riemannian holonomy",
                "author": "Kovalev, A.",
                "year": 2003
            },
            {
                "title": "Wikipedia: G₂ Manifold",
                "link": "https://en.wikipedia.org/wiki/G2_manifold"
            }
        ]
    },
    "calabi-yau": {
        "id": "calabi-yau",
        "title": "Calabi-Yau Manifolds",
        "year": 1954,
        "equation": "R_ij̄ = 0, c₁(M) = 0",
        "summary": "Complex manifolds with SU(n) holonomy used in string theory compactifications. Preserve supersymmetry through Ricci-flat geometry.",
        "badge": "established",
        "description": "Calabi-Yau manifolds are special geometric spaces that preserve supersymmetry when used for dimensional compactification. They are central to string theory and F-theory compactifications. In the 2T framework, CY4 concepts inform the topology.",
        "key_properties": [
            {
                "property": "Complex Structure",
                "value": "Kähler manifold"
            },
            {
                "property": "Ricci Curvature",
                "value": "Ricci-flat"
            },
            {
                "property": "First Chern Class",
                "value": "c₁(M) = 0"
            },
            {
                "property": "Supersymmetry",
                "value": "N=1 SUSY preservation"
            }
        ],
        "cy_types": [
            {
                "type": "CY1",
                "complex_dim": 1,
                "real_dim": 2,
                "application": "Torus T²"
            },
            {
                "type": "CY2",
                "complex_dim": 2,
                "real_dim": 4,
                "application": "K3 surface (F-theory)"
            },
            {
                "type": "CY3",
                "complex_dim": 3,
                "real_dim": 6,
                "application": "Heterotic string (10D → 4D)"
            },
            {
                "type": "CY4",
                "complex_dim": 4,
                "real_dim": 8,
                "application": "F-theory, PM's 2T framework"
            }
        ],
        "hodge_numbers": {
            "h11": 4,
            "h21": 0,
            "chi_bare": 8,
            "chi_eff": 144,
            "description": "Flux-dressed effective Euler characteristic differs from bare topology"
        },
        "generation_formula": {
            "formula": "n_gen = χ_eff/48 = 144/48 = 3",
            "chi_A": 72,
            "chi_B": 72,
            "divisor": 48,
            "description": "SO(10) embedding factor from F-theory"
        },
        "kklt_mechanism": {
            "modulus_vev": "φ_M = 2.493 M_Pl",
            "description": "Flux stabilization through KKLT mechanism changes effective topology",
            "flux_dressing": "χ_eff = χ_bare + Δχ_flux"
        },
        "pm_2t_framework": {
            "structure": "13D shadow → G₂ compactification",
            "mirror_symmetry": "CY4_A and CY4_B are mirror pairs",
            "chi_total": 144,
            "shared_timelike": "Both halves share R^(1,1) signature"
        },
        "references": [
            {
                "title": "Calabi's Conjecture and Some New Results",
                "author": "Yau, S.T.",
                "year": 1977
            },
            {
                "title": "Evidence for F-Theory",
                "author": "Vafa, C.",
                "year": 1996,
                "link": "https://arxiv.org/abs/hep-th/9602022"
            },
            {
                "title": "de Sitter Vacua in String Theory",
                "author": "Kachru, Kallosh, Linde, Trivedi",
                "year": 2003,
                "link": "https://arxiv.org/abs/hep-th/0301240"
            },
            {
                "title": "Wikipedia: Calabi-Yau Manifold",
                "link": "https://en.wikipedia.org/wiki/Calabi%E2%80%93Yau_manifold"
            }
        ]
    }
}

# Add to the unification category (or create if doesn't exist)
if "unification" not in foundations_data["foundations"]:
    foundations_data["foundations"]["unification"] = {
        "category": "Extra Dimensions & Unification",
        "description": "Theoretical frameworks for unifying forces through extra dimensions and higher symmetries.",
        "items": []
    }

# Check if entries already exist and update them
existing_ids = {item["id"] for item in foundations_data["foundations"]["unification"]["items"]}

for foundation_id, foundation_data in geometry_foundations.items():
    if foundation_id in existing_ids:
        # Update existing entry
        for i, item in enumerate(foundations_data["foundations"]["unification"]["items"]):
            if item["id"] == foundation_id:
                # Preserve link field, update everything else
                foundation_data["link"] = f"{foundation_id}.html"
                foundations_data["foundations"]["unification"]["items"][i] = {
                    "id": foundation_data["id"],
                    "title": foundation_data["title"],
                    "year": foundation_data["year"],
                    "equation": foundation_data["equation"],
                    "summary": foundation_data["summary"],
                    "badge": foundation_data["badge"],
                    "link": f"{foundation_id}.html",
                    "full_content": foundation_data
                }
                print(f"[OK] Updated {foundation_id} in foundations_data.json")
                break
    else:
        # Add new entry
        foundations_data["foundations"]["unification"]["items"].append({
            "id": foundation_data["id"],
            "title": foundation_data["title"],
            "year": foundation_data["year"],
            "equation": foundation_data["equation"],
            "summary": foundation_data["summary"],
            "badge": foundation_data["badge"],
            "link": f"{foundation_id}.html",
            "full_content": foundation_data
        })
        print(f"[OK] Added {foundation_id} to foundations_data.json")

# Write back to foundations_data.json
with open(foundations_json_path, 'w', encoding='utf-8') as f:
    json.dump(foundations_data, f, indent=2, ensure_ascii=False)

print(f"\n[OK] Successfully updated {foundations_json_path}")
print(f"\nAdded/updated foundations:")
for fid in geometry_foundations.keys():
    print(f"  - {fid}")
