import json
import sys

# Set UTF-8 encoding for stdout
sys.stdout.reconfigure(encoding='utf-8')

# Read the file
with open(r'h:\Github\PrincipiaMetaphysica\AutoGenerated\theory_output.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

# Find Section 3
section3 = data['sections']['3']

# Track changes
changes_made = 0

# Process each subsection
for subsection in section3.get('subsections', []):
    subsec_id = subsection.get('id', 'unknown')
    subsec_num = subsection.get('number', 'unknown')

    for block in subsection.get('content_blocks', []):
        if block.get('type') == 'equation':
            if 'latex' not in block:
                # Add latex field with the content
                block['latex'] = block.get('content', '')
                changes_made += 1
                print(f'Added latex field to equation in {subsec_num} ({subsec_id})')

# Write the updated data back
with open(r'h:\Github\PrincipiaMetaphysica\AutoGenerated\theory_output.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print(f'\nTotal changes made: {changes_made}')
print('File updated successfully!')
