#!/usr/bin/env python3
"""
Migrate ALL sections from legacy content_blocks to camelCase contentBlocks format.
Ensures equation blocks use "latex" field instead of "content" for formulas.
"""

import json
import sys

def migrate_content_blocks_to_camel_case(subsection):
    """Convert content_blocks (underscore) to contentBlocks (camelCase)."""
    if "content_blocks" not in subsection:
        return subsection

    content_blocks = subsection.pop("content_blocks")
    new_content_blocks = []

    for block in content_blocks:
        block_type = block.get("type", "")

        if block_type == "paragraph":
            # Convert paragraph to text type
            new_content_blocks.append({
                "type": "text",
                "content": block.get("content", "")
            })

        elif block_type == "equation":
            # Convert equation block to formula with latex field
            new_block = {
                "type": "formula",
                "latex": block.get("content", "").replace("$$", "").strip()
            }
            if "label" in block:
                new_block["label"] = block["label"]
            new_content_blocks.append(new_block)

        elif block_type == "list":
            # Keep list as-is but wrap in proper structure
            new_content_blocks.append({
                "type": "list",
                "items": block.get("items", [])
            })

        elif block_type == "code":
            # Keep code as-is
            new_block = {
                "type": "code",
                "content": block.get("content", "")
            }
            if "language" in block:
                new_block["language"] = block["language"]
            if "label" in block:
                new_block["label"] = block["label"]
            new_content_blocks.append(new_block)

        else:
            # Unknown type, keep as-is
            new_content_blocks.append(block)

    subsection["contentBlocks"] = new_content_blocks
    return subsection


def migrate_all_sections(data):
    """Migrate all sections that have legacy content_blocks."""
    if "sections" not in data:
        print("ERROR: No 'sections' key found in data")
        return 0

    sections = data["sections"]
    migrated_count = 0

    for section_id, section in sections.items():
        section_title = section.get('title', 'Unknown')

        # Migrate top-level content_blocks
        if "content_blocks" in section:
            print(f"  Migrating section {section_id} (top-level)")
            migrate_content_blocks_to_camel_case(section)
            migrated_count += 1

        # Migrate subsections
        if "subsections" in section:
            for subsection in section["subsections"]:
                if "content_blocks" in subsection:
                    print(f"  Migrating section {section_id} (subsection)")
                    migrate_content_blocks_to_camel_case(subsection)
                    migrated_count += 1

    return migrated_count


def main():
    input_file = r"h:\Github\PrincipiaMetaphysica\AutoGenerated\theory_output.json"

    print(f"Reading {input_file}...")
    with open(input_file, "r", encoding="utf-8") as f:
        data = json.load(f)

    print("\nMigrating all sections with legacy content_blocks...")
    count = migrate_all_sections(data)

    if count > 0:
        print(f"\nMigrated {count} subsections")

        # Write back to file
        print(f"\nWriting to {input_file}...")
        with open(input_file, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, ensure_ascii=False)

        print("File updated successfully")
        return 0
    else:
        print("\nNo legacy content_blocks found")
        return 0


if __name__ == "__main__":
    sys.exit(main())
