#!/usr/bin/env python3
"""
Migrate Appendix H from legacy content_blocks to camelCase contentBlocks format.
Ensures equation blocks use "latex" field instead of "content" for formulas.
"""

import json
import sys

def migrate_content_blocks_to_camel_case(subsection):
    """Convert content_blocks (underscore) to contentBlocks (camelCase)."""
    if "content_blocks" not in subsection:
        return subsection

    content_blocks = subsection.pop("content_blocks")
    new_content_blocks = []

    for block in content_blocks:
        block_type = block.get("type", "")

        if block_type == "paragraph":
            # Convert paragraph to text type
            new_content_blocks.append({
                "type": "text",
                "content": block.get("content", "")
            })

        elif block_type == "equation":
            # Convert equation block to formula with latex field
            new_block = {
                "type": "formula",
                "latex": block.get("content", "").replace("$$", "").strip()
            }
            if "label" in block:
                new_block["label"] = block["label"]
            new_content_blocks.append(new_block)

        elif block_type == "list":
            # Keep list as-is but wrap in proper structure
            new_content_blocks.append({
                "type": "list",
                "items": block.get("items", [])
            })

        elif block_type == "code":
            # Keep code as-is
            new_block = {
                "type": "code",
                "content": block.get("content", "")
            }
            if "language" in block:
                new_block["language"] = block["language"]
            if "label" in block:
                new_block["label"] = block["label"]
            new_content_blocks.append(new_block)

        else:
            # Unknown type, keep as-is
            new_content_blocks.append(block)

    subsection["contentBlocks"] = new_content_blocks
    return subsection


def migrate_appendix_h(data):
    """Migrate Appendix H structure."""
    # Navigate to sections
    if "sections" not in data:
        print("ERROR: No 'sections' key found in data")
        return False

    sections = data["sections"]

    # Find Appendix H
    appendix_h = sections.get("H")
    if not appendix_h:
        print("ERROR: Appendix H not found")
        return False

    print(f"Found Appendix H: {appendix_h.get('title')}")

    # Migrate subsections
    if "subsections" in appendix_h:
        for subsection in appendix_h["subsections"]:
            if "content_blocks" in subsection:
                print(f"  Migrating subsection: {subsection.get('title')}")
                migrate_content_blocks_to_camel_case(subsection)
                print(f"    Converted content_blocks to contentBlocks")

    return True


def main():
    input_file = r"h:\Github\PrincipiaMetaphysica\AutoGenerated\theory_output.json"

    print(f"Reading {input_file}...")
    with open(input_file, "r", encoding="utf-8") as f:
        data = json.load(f)

    print("\nMigrating Appendix H...")
    if migrate_appendix_h(data):
        print("\nMigration successful")

        # Write back to file
        print(f"\nWriting to {input_file}...")
        with open(input_file, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, ensure_ascii=False)

        print("File updated successfully")
        return 0
    else:
        print("\nMigration failed")
        return 1


if __name__ == "__main__":
    sys.exit(main())
