#!/usr/bin/env python3
"""
Dark Matter Derivation Validation Script
=========================================

This script validates all dark matter derivations by:
1. Loading the Python derivation module
2. Loading the JSON derivation chain
3. Cross-checking results
4. Generating a validation report

Usage:
    python validate_dark_matter.py

Copyright (c) 2025-2026 Andrew Keith Watts. All rights reserved.

Dedicated To:
    My Wife: Elizabeth May Watts
    Our Messiah: Jesus Of Nazareth
"""

import sys
import io
if sys.platform == 'win32':
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

import json
from pathlib import Path
from dark_matter_derivations import DarkMatterDerivations

def load_json_chain():
    """Load the JSON derivation chain."""
    json_path = Path(__file__).parent.parent.parent / "AutoGenerated" / "derivations" / "dark_matter_chain.json"
    with open(json_path, 'r', encoding='utf-8') as f:
        return json.load(f)

def validate_derivations():
    """Validate all dark matter derivations."""
    print("=" * 70)
    print("DARK MATTER DERIVATION VALIDATION")
    print("=" * 70)

    # Load Python derivations
    print("\n[1/4] Loading Python derivation module...")
    dm = DarkMatterDerivations(chi_eff=144, b3=24, d_over_R=0.12, re_T=9.865)
    python_result = dm.full_derivation_chain()
    print("     DONE: Python module loaded successfully")

    # Load JSON chain
    print("\n[2/4] Loading JSON derivation chain...")
    json_chain = load_json_chain()
    print(f"     DONE: JSON chain loaded with {len(json_chain['derivation_chain'])} steps")

    # Cross-check key results
    print("\n[3/4] Cross-checking key results...")

    checks = []

    # Check 1: Temperature ratio
    py_T_ratio = python_result['summary']['T_ratio']
    json_T_ratio = json_chain['derivation_overview']['key_outputs']['T_ratio']
    checks.append({
        'name': 'Temperature Ratio (T\'/T)',
        'python': py_T_ratio,
        'json': json_T_ratio,
        'match': abs(py_T_ratio - json_T_ratio) < 0.001
    })

    # Check 2: DM abundance
    py_omega = python_result['summary']['Omega_DM_over_Omega_b']
    json_omega = json_chain['derivation_overview']['key_outputs']['Omega_DM_over_Omega_b']
    checks.append({
        'name': 'DM Abundance (Omega_DM/Omega_b)',
        'python': py_omega,
        'json': json_omega,
        'match': abs(py_omega - json_omega) < 0.01
    })

    # Check 3: Portal coupling
    py_g = python_result['summary']['g_portal']
    json_g = json_chain['derivation_overview']['key_outputs']['g_portal']
    checks.append({
        'name': 'Portal Coupling (g_portal)',
        'python': py_g,
        'json': json_g,
        'match': abs(py_g - json_g) / py_g < 0.01  # 1% tolerance
    })

    # Check 4: Cross-section
    py_sigma = python_result['summary']['sigma_SI_cm2']
    json_sigma = json_chain['derivation_overview']['key_outputs']['sigma_SI_100GeV']
    checks.append({
        'name': 'Direct Detection Cross-Section (sigma_SI)',
        'python': py_sigma,
        'json': json_sigma,
        'match': abs(py_sigma - json_sigma) / max(py_sigma, json_sigma) < 0.1  # 10% tolerance
    })

    # Print results
    all_match = True
    for check in checks:
        status = "PASS" if check['match'] else "FAIL"
        if not check['match']:
            all_match = False
        print(f"     {status}: {check['name']}")
        print(f"          Python: {check['python']}")
        print(f"          JSON:   {check['json']}")

    if all_match:
        print("\n     ALL CHECKS PASSED")
    else:
        print("\n     WARNING: Some checks failed")

    # Validate Wolfram queries
    print("\n[4/4] Validating Wolfram queries...")
    py_query_count = len(python_result['all_wolfram_queries'])
    json_query_count = json_chain['summary_wolfram_queries']['total_count']

    print(f"     Python module: {py_query_count} queries")
    print(f"     JSON chain: {json_query_count} queries")

    if py_query_count == json_query_count:
        print(f"     PASS: Query count matches")
    else:
        print(f"     WARNING: Query count mismatch")

    # Final summary
    print("\n" + "=" * 70)
    print("VALIDATION SUMMARY")
    print("=" * 70)
    print(f"Temperature Ratio:     {py_T_ratio:.3f}")
    print(f"DM Abundance:          {py_omega:.2f}")
    print(f"  Planck 2018:         5.38 +/- 0.15")
    print(f"  Agreement:           {python_result['summary']['planck_agreement']}")
    print(f"Portal Coupling:       {py_g:.2e}")
    print(f"Cross-Section:         {py_sigma:.2e} cm^2")
    print(f"  LZ 2023 Limit:       1.50e-48 cm^2")
    print(f"  Status:              {python_result['summary']['detection_status']}")
    print(f"\nWolfram Queries:       {py_query_count} total")
    print(f"Derivation Steps:      {len(json_chain['derivation_chain'])}")
    print(f"\nOverall Status:        {'ALL VALIDATED' if all_match else 'VALIDATION ISSUES'}")
    print("=" * 70)

    return all_match

if __name__ == "__main__":
    try:
        success = validate_derivations()
        sys.exit(0 if success else 1)
    except Exception as e:
        print(f"\nERROR: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
