#!/usr/bin/env python3
"""
PM Publication Plots v16.1
==========================

Generates publication-quality figures for the paper and website.

This module creates four key plots for Principia Metaphysica v16.1:
1. Neutrino mixing (θ₂₃ vs δ_CP) with 3σ NuFIT contours
2. Hubble tension resolution (bar chart with error bars)
3. H(z) evolution history (log-log plot)
4. Theory residuals (σ-deviation horizontal bars)

Copyright (c) 2025-2026 Andrew Keith Watts. All rights reserved.

Dedicated To:
    My Wife: Elizabeth May Watts
    Our Messiah: Jesus Of Nazareth
"""

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.patches import Ellipse
import numpy as np
import json
import os
from pathlib import Path
from typing import Dict, Any, Optional, Tuple

# Import Single Source of Truth for derived constants
try:
    from core.FormulasRegistry import get_registry
    _reg = get_registry()
    _REGISTRY_AVAILABLE = True
except ImportError:
    _reg = None
    _REGISTRY_AVAILABLE = False

# Module-level constant for tzimtzum_pressure default (w0 = -23/24)
_TZIMTZUM_DEFAULT = _reg.tzimtzum_pressure if _REGISTRY_AVAILABLE else 0.9583


def set_publication_style():
    """Set publication-quality matplotlib style."""
    plt.style.use('seaborn-v0_8-whitegrid')
    plt.rcParams.update({
        "font.family": "serif",
        "font.serif": ["Times New Roman", "DejaVu Serif"],
        "text.usetex": False,
        "axes.labelsize": 14,
        "xtick.labelsize": 12,
        "ytick.labelsize": 12,
        "legend.fontsize": 11,
        "figure.dpi": 300,
        "savefig.dpi": 300,
        "axes.grid": True,
        "grid.alpha": 0.3,
    })


def load_theory_data(theory_path: str = "AutoGenerated/theory_output.json") -> Dict[str, Any]:
    """Load theory output data from JSON file.

    Args:
        theory_path: Path to theory output JSON file

    Returns:
        Dictionary containing theory parameters
    """
    # Construct absolute path
    if not os.path.isabs(theory_path):
        base_dir = Path(__file__).parent.parent
        theory_path = os.path.join(base_dir, theory_path)

    try:
        with open(theory_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
        return data.get('parameters', {})
    except FileNotFoundError:
        print(f"Warning: {theory_path} not found. Using default values.")
        return {}
    except Exception as e:
        print(f"Error loading theory data: {e}")
        return {}


def plot_neutrino_mixing_contours(
    output_path: str = "AutoGenerated/plots/neutrino_mixing_contours_v16_1.png",
    theory_data: Optional[Dict] = None
):
    """
    Plot 1: Neutrino Mixing with 3σ Contours

    Shows θ₂₃ vs δ_CP with NuFIT 6.0 confidence ellipses for both
    Normal Ordering (NO) and Inverted Ordering (IO). PM prediction
    marked with X.

    Args:
        output_path: Where to save the plot
        theory_data: Theory output parameters
    """
    set_publication_style()
    fig, ax = plt.subplots(figsize=(8, 6))

    # PM prediction
    if theory_data:
        theta23_pm = theory_data.get('neutrino.theta_23_pred', {}).get('value', 46.08)
        delta_cp_pm = theory_data.get('neutrino.delta_CP_pred', {}).get('value', 232.5)
    else:
        theta23_pm = 46.08
        delta_cp_pm = 232.5

    # NuFIT 6.0 central values (Normal Ordering)
    theta23_no = 45.0  # degrees
    delta_cp_no = 194.0  # degrees

    # NuFIT 6.0 central values (Inverted Ordering)
    theta23_io = 45.1
    delta_cp_io = 286.0

    # 3σ uncertainties (approximate ellipse parameters)
    # These are rough estimates from NuFIT 6.0 contour plots
    sigma_theta23 = 1.0  # 1σ uncertainty
    sigma_delta_cp = 25.0  # 1σ uncertainty

    # Plot 3σ contours (approximate as ellipses)
    ellipse_no = Ellipse(
        (delta_cp_no, theta23_no),
        width=6*sigma_delta_cp,
        height=6*sigma_theta23,
        facecolor='blue',
        edgecolor='darkblue',
        alpha=0.2,
        linewidth=2,
        label='NuFIT 6.0 NO (3σ)'
    )
    ax.add_patch(ellipse_no)

    ellipse_io = Ellipse(
        (delta_cp_io, theta23_io),
        width=6*sigma_delta_cp,
        height=6*sigma_theta23,
        facecolor='green',
        edgecolor='darkgreen',
        alpha=0.2,
        linewidth=2,
        label='NuFIT 6.0 IO (3σ)'
    )
    ax.add_patch(ellipse_io)

    # Mark central values
    ax.plot(delta_cp_no, theta23_no, 'o', color='darkblue', markersize=8,
            label='NuFIT NO best fit')
    ax.plot(delta_cp_io, theta23_io, 's', color='darkgreen', markersize=8,
            label='NuFIT IO best fit')

    # PM prediction
    ax.plot(delta_cp_pm, theta23_pm, 'X', color='red', markersize=15,
            markeredgewidth=2, label=f'PM v16.1: ({delta_cp_pm:.1f}°, {theta23_pm:.2f}°)',
            zorder=10)

    # Labels and formatting
    ax.set_xlabel(r'$\delta_{CP}$ (degrees)', fontsize=14)
    ax.set_ylabel(r'$\theta_{23}$ (degrees)', fontsize=14)
    ax.set_title('Neutrino Mixing: PM Prediction vs NuFIT 6.0', fontsize=16, pad=20)

    # Set reasonable axis limits
    ax.set_xlim(100, 360)
    ax.set_ylim(42, 49)

    ax.legend(loc='upper right', fontsize=10)
    ax.grid(True, alpha=0.3)

    # Save
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    plt.tight_layout()
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    plt.close()
    print(f"[OK] Neutrino mixing contours saved to {output_path}")


def plot_hubble_tension(
    output_path: str = "AutoGenerated/plots/hubble_tension_v16_1.png",
    theory_data: Optional[Dict] = None
):
    """
    Plot 2: Hubble Tension Resolution

    Bar chart comparing:
    - CMB (Planck): 67.4 ± 0.5 km/s/Mpc
    - SH0ES (local): 73.04 ± 1.04 km/s/Mpc
    - PM prediction: 73.08 km/s/Mpc

    Args:
        output_path: Where to save the plot
        theory_data: Theory output parameters
    """
    set_publication_style()
    fig, ax = plt.subplots(figsize=(8, 6))

    # Data
    measurements = ['CMB\n(Planck 2018)', 'SH0ES\n(Local Distance Ladder)', 'PM v16.1\n(G₂ + EDE)']
    h0_values = [67.4, 73.04, 73.08]
    h0_errors = [0.5, 1.04, 0.0]  # PM is a prediction, no error bar
    colors = ['#3498db', '#e74c3c', '#2ecc71']  # Blue, Red, Green

    # Create bars
    bars = ax.bar(measurements, h0_values, yerr=h0_errors, capsize=8,
                  color=colors, alpha=0.8, edgecolor='black', linewidth=1.5)

    # Add value labels on bars
    for i, (bar, val, err) in enumerate(zip(bars, h0_values, h0_errors)):
        if err > 0:
            label = f'{val:.2f} ± {err:.2f}'
        else:
            label = f'{val:.2f}'
        ax.text(bar.get_x() + bar.get_width()/2, val + err + 0.5, label,
                ha='center', va='bottom', fontsize=11, fontweight='bold')

    # Horizontal lines for reference
    ax.axhline(y=67.4, color='#3498db', linestyle='--', alpha=0.5, linewidth=1)
    ax.axhline(y=73.04, color='#e74c3c', linestyle='--', alpha=0.5, linewidth=1)

    # Labels and formatting
    ax.set_ylabel(r'$H_0$ ($\mathrm{km\,s^{-1}\,Mpc^{-1}}$)', fontsize=14)
    ax.set_title('Hubble Tension Resolution: Early Dark Energy Mechanism', fontsize=16, pad=20)
    ax.set_ylim(65, 76)
    ax.grid(axis='y', alpha=0.3)

    # Add annotation
    ax.text(0.02, 0.98,
            'PM resolves 5σ tension\nvia geometric EDE pulse at z=3540',
            transform=ax.transAxes, fontsize=10,
            verticalalignment='top', bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))

    # Save
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    plt.tight_layout()
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    plt.close()
    print(f"[OK] Hubble tension plot saved to {output_path}")


def plot_hubble_evolution(
    output_path: str = "AutoGenerated/plots/hubble_evolution_v16_1.png",
    theory_data: Optional[Dict] = None
):
    """
    Plot 3: H(z) Evolution History

    Log-log plot showing Hubble parameter evolution with redshift.
    Compares ΛCDM baseline (dashed) with PM v16.1 + EDE pulse (solid).
    Marks the z=3540 transition point.

    Args:
        output_path: Where to save the plot
        theory_data: Theory output parameters
    """
    set_publication_style()
    fig, ax = plt.subplots(figsize=(9, 6))

    # Redshift range
    z = np.logspace(-2, 4, 500)  # z from 0.01 to 10000
    a = 1 / (1 + z)  # Scale factor

    # Cosmological parameters
    H0 = 73.08  # PM prediction (km/s/Mpc)
    H0_lcdm = 67.4  # Planck ΛCDM
    Omega_m = 0.315
    Omega_Lambda = 1 - Omega_m

    # ΛCDM Hubble parameter
    H_lcdm = H0_lcdm * np.sqrt(Omega_m * (1 + z)**3 + Omega_Lambda)

    # PM with EDE pulse at z=3540
    z_ede = 3540
    f_ede = 0.10  # ~10% fractional energy density at peak
    width = 0.3   # Width of Gaussian pulse in log(1+z)

    # Early Dark Energy contribution (Gaussian pulse)
    Omega_ede = f_ede * np.exp(-((np.log(1 + z) - np.log(1 + z_ede))**2) / (2 * width**2))

    # PM Hubble parameter with EDE
    H_pm = H0 * np.sqrt(Omega_m * (1 + z)**3 + Omega_Lambda + Omega_ede * (1 + z)**4)

    # Plot
    ax.loglog(z, H_lcdm, '--', color='#3498db', linewidth=2.5, label='ΛCDM (Planck)', alpha=0.7)
    ax.loglog(z, H_pm, '-', color='#2ecc71', linewidth=2.5, label='PM v16.1 (with EDE pulse)')

    # Mark EDE transition
    H_at_ede = H0 * np.sqrt(Omega_m * (1 + z_ede)**3 + Omega_Lambda + f_ede * (1 + z_ede)**4)
    ax.plot(z_ede, H_at_ede, 'o', color='red', markersize=10,
            label=f'EDE pulse at z={z_ede}', zorder=5)

    # Vertical line at z_ede
    ax.axvline(x=z_ede, color='red', linestyle=':', alpha=0.5, linewidth=1.5)

    # Labels and formatting
    ax.set_xlabel('Redshift z', fontsize=14)
    ax.set_ylabel(r'$H(z)$ ($\mathrm{km\,s^{-1}\,Mpc^{-1}}$)', fontsize=14)
    ax.set_title('Hubble Parameter Evolution: EDE Mechanism from G₂ Moduli', fontsize=16, pad=20)

    ax.set_xlim(0.01, 1e4)
    ax.set_ylim(60, 1e6)

    ax.legend(loc='upper left', fontsize=11)
    ax.grid(True, which='both', alpha=0.3)

    # Add annotation
    ax.text(0.98, 0.02,
            'EDE pulse resolves Hubble tension\nwhile preserving CMB fit',
            transform=ax.transAxes, fontsize=10,
            verticalalignment='bottom', horizontalalignment='right',
            bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))

    # Save
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    plt.tight_layout()
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    plt.close()
    print(f"[OK] H(z) evolution plot saved to {output_path}")


def plot_theory_residuals(
    output_path: str = "AutoGenerated/plots/theory_residuals_v16_1.png",
    theory_data: Optional[Dict] = None
):
    """
    Plot 4: Theory Residuals

    Horizontal bar chart showing σ-deviations from observation for:
    - H₀ (Hubble constant)
    - w₀ (dark energy equation of state)
    - θ₂₃ (atmospheric mixing angle)
    - δ_CP (CP violating phase)

    Color coded: green (<1σ), orange (1-2σ), red (>2σ)

    Args:
        output_path: Where to save the plot
        theory_data: Theory output parameters
    """
    set_publication_style()
    fig, ax = plt.subplots(figsize=(9, 6))

    # Data: parameter, PM value, observed value, uncertainty (1σ)
    # v16.2 Thawing Quintessence: w₀ = -23/24 ≈ -0.9583
    if theory_data:
        theta23_pm = theory_data.get('neutrino.theta_23_pred', {}).get('value', 46.08)
        delta_cp_pm = theory_data.get('neutrino.delta_CP_pred', {}).get('value', 232.5)
        w0_pm = theory_data.get('cosmology.w0_derived', {}).get('value', -_TZIMTZUM_DEFAULT)
    else:
        theta23_pm = 46.08
        delta_cp_pm = 232.5
        w0_pm = -_TZIMTZUM_DEFAULT  # v16.2: -23/24 from b₃=24 thawing

    # Calculate residuals in units of σ
    params = {
        r'$H_0$ (km/s/Mpc)': {
            'pm': 73.08,
            'obs': 73.04,  # SH0ES
            'sigma': 1.04,
        },
        r'$w_0$ (DE EoS)': {
            'pm': w0_pm,
            'obs': -0.957,  # DESI 2025 thawing constraint
            'sigma': 0.067,
        },
        r'$\theta_{23}$ (deg)': {
            'pm': theta23_pm,
            'obs': 45.0,  # NuFIT NO
            'sigma': 1.0,
        },
        r'$\delta_{CP}$ (deg)': {
            'pm': delta_cp_pm,
            'obs': 194.0,  # NuFIT NO
            'sigma': 25.0,
        },
    }

    # Calculate σ deviations
    labels = list(params.keys())
    sigma_devs = []
    colors_list = []

    for param_name, data in params.items():
        deviation = abs(data['pm'] - data['obs']) / data['sigma']
        sigma_devs.append(deviation)

        # Color code based on deviation
        if deviation < 1.0:
            colors_list.append('#2ecc71')  # Green
        elif deviation < 2.0:
            colors_list.append('#f39c12')  # Orange
        else:
            colors_list.append('#e74c3c')  # Red

    # Create horizontal bar chart
    y_pos = np.arange(len(labels))
    bars = ax.barh(y_pos, sigma_devs, color=colors_list, alpha=0.8,
                   edgecolor='black', linewidth=1.5)

    # Add vertical lines for reference
    ax.axvline(x=1.0, color='green', linestyle='--', alpha=0.5, linewidth=2, label='1σ')
    ax.axvline(x=2.0, color='orange', linestyle='--', alpha=0.5, linewidth=2, label='2σ')
    ax.axvline(x=3.0, color='red', linestyle='--', alpha=0.5, linewidth=2, label='3σ')

    # Add value labels on bars
    for i, (bar, sigma) in enumerate(zip(bars, sigma_devs)):
        ax.text(sigma + 0.05, bar.get_y() + bar.get_height()/2,
                f'{sigma:.2f}σ',
                va='center', fontsize=11, fontweight='bold')

    # Labels and formatting
    ax.set_yticks(y_pos)
    ax.set_yticklabels(labels, fontsize=12)
    ax.set_xlabel('Deviation from Observation (σ)', fontsize=14)
    ax.set_title('PM v16.1 Predictions: Agreement with Observation', fontsize=16, pad=20)
    ax.set_xlim(0, max(sigma_devs) + 0.5)
    ax.grid(axis='x', alpha=0.3)
    ax.legend(loc='upper right', fontsize=10)

    # Add summary statistics
    avg_sigma = np.mean(sigma_devs)
    ax.text(0.98, 0.02,
            f'Average deviation: {avg_sigma:.2f}σ\nAll predictions <2σ',
            transform=ax.transAxes, fontsize=10,
            verticalalignment='bottom', horizontalalignment='right',
            bbox=dict(boxstyle='round', facecolor='lightgreen', alpha=0.5))

    # Save
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    plt.tight_layout()
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    plt.close()
    print(f"[OK] Theory residuals plot saved to {output_path}")


def generate_all_plots(theory_path: str = "AutoGenerated/theory_output.json"):
    """
    Generate all four publication plots for PM v16.1.

    Args:
        theory_path: Path to theory_output.json file
    """
    print("=" * 70)
    print("PM v16.1 PUBLICATION PLOTS")
    print("=" * 70)
    print()

    # Load theory data
    theory_data = load_theory_data(theory_path)

    # Generate plots
    print("Generating plots...")
    print()

    plot_neutrino_mixing_contours(theory_data=theory_data)
    plot_hubble_tension(theory_data=theory_data)
    plot_hubble_evolution(theory_data=theory_data)
    plot_theory_residuals(theory_data=theory_data)

    print()
    print("=" * 70)
    print("[SUCCESS] All plots generated successfully!")
    print("=" * 70)
    print()
    print("Output directory: AutoGenerated/plots/")
    print("Files:")
    print("  1. neutrino_mixing_contours_v16_1.png")
    print("  2. hubble_tension_v16_1.png")
    print("  3. hubble_evolution_v16_1.png")
    print("  4. theory_residuals_v16_1.png")
    print()
    print("All plots saved at 300 DPI for publication quality.")


if __name__ == "__main__":
    generate_all_plots()
