"""
Add terms and HTML for priority formulas identified by Gemini.
"""

import json
import sys
sys.stdout.reconfigure(encoding='utf-8')

with open('h:/Github/PrincipiaMetaphysica/AutoGenerated/formulas.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

formulas = data.get('formulas', {})

# 1. g2-holonomy
formulas['g2-holonomy']['terms'] = {
    'Hol(g)': {'description': 'Holonomy group of the metric g', 'symbol': 'Hol(g)'},
    'G2': {'description': 'Exceptional Lie group G2 (14-dimensional)', 'symbol': 'G₂'},
    'eta': {'description': 'Covariantly constant 3-form defining G2 structure', 'symbol': 'η'},
    'nabla': {'description': 'Levi-Civita connection (covariant derivative)', 'symbol': '∇'}
}
formulas['g2-holonomy']['html'] = '''<span class="formula-var" data-term="Hol">Hol(g)<span class="var-tooltip"><span class="var-name">Hol(g)</span><span class="var-description">Holonomy group of the metric g</span></span></span>
<span class="formula-op"> ⊆ </span>
<span class="formula-var" data-term="G2">G₂<span class="var-tooltip"><span class="var-name">G₂</span><span class="var-description">Exceptional Lie group G2 (14-dimensional)</span></span></span>
<span class="formula-op"> ⟺ ∃</span>
<span class="formula-var" data-term="eta">η<span class="var-tooltip"><span class="var-name">η</span><span class="var-description">Covariantly constant 3-form defining G2 structure</span></span></span>
<span class="formula-op">:</span>
<span class="formula-var" data-term="nabla">∇η<span class="var-tooltip"><span class="var-name">∇η = 0</span><span class="var-description">Parallel transport preserves the 3-form</span></span></span>
<span class="formula-op"> = 0</span>'''
print('Added: g2-holonomy')

# 2. 26d-signature
formulas['26d-signature']['terms'] = {
    'M26': {'description': '26-dimensional ancestral bulk manifold', 'symbol': 'M²⁶'},
    '24': {'description': '24 spatial dimensions (from Leech lattice)', 'symbol': '24'},
    '2': {'description': '2 temporal dimensions (for Sp(2,R) gauge)', 'symbol': '2'}
}
formulas['26d-signature']['html'] = '''<span class="formula-op">Signature(</span>
<span class="formula-var" data-term="M26">M<sup>26</sup><span class="var-tooltip"><span class="var-name">M²⁶</span><span class="var-description">26-dimensional ancestral bulk manifold</span></span></span>
<span class="formula-op">) = (</span>
<span class="formula-var" data-term="24">24<span class="var-tooltip"><span class="var-name">24</span><span class="var-description">24 spatial dimensions (from Leech lattice uniqueness)</span></span></span>
<span class="formula-op">,</span>
<span class="formula-var" data-term="2">2<span class="var-tooltip"><span class="var-name">2</span><span class="var-description">2 temporal dimensions (for Sp(2,R) gauge fixing)</span></span></span>
<span class="formula-op">)</span>'''
print('Added: 26d-signature')

# 3. generation-theorem
formulas['generation-theorem']['terms'] = {
    '24': {'description': 'Third Betti number b₃ of G2 manifold', 'symbol': 'b₃'},
    '3': {'description': 'Number of fermion generations', 'symbol': 'n_gen'},
    '8': {'description': 'Dimension of spinor representation', 'symbol': 'dim(spinor)'}
}
formulas['generation-theorem']['html'] = '''<span class="formula-var" data-term="b3">24<span class="var-tooltip"><span class="var-name">b₃ = 24</span><span class="var-description">Third Betti number of TCS G2 manifold #187</span></span></span>
<span class="formula-op"> = </span>
<span class="formula-var" data-term="ngen">3<span class="var-tooltip"><span class="var-name">n_gen = 3</span><span class="var-description">Number of fermion generations (quarks and leptons)</span></span></span>
<span class="formula-op"> × </span>
<span class="formula-var" data-term="spinor">8<span class="var-tooltip"><span class="var-name">8</span><span class="var-description">Dimension of spinor representation in each generation</span></span></span>'''
print('Added: generation-theorem')

# 4. pmns-theta-12
formulas['pmns-theta-12']['terms'] = {
    'theta_12': {'description': 'Solar neutrino mixing angle (θ₁₂)', 'symbol': 'θ₁₂'},
    'b3': {'description': 'Third Betti number = 24', 'symbol': 'b₃'},
    'b2': {'description': 'Second Betti number = 4', 'symbol': 'b₂'},
    'n_gen': {'description': 'Number of generations = 3', 'symbol': 'n_gen'},
    'chi_eff': {'description': 'Effective Euler characteristic = 144', 'symbol': 'χ_eff'}
}
formulas['pmns-theta-12']['html'] = '''<span class="formula-op">sin(</span>
<span class="formula-var" data-term="theta12">θ₁₂<span class="var-tooltip"><span class="var-name">θ₁₂</span><span class="var-description">Solar neutrino mixing angle</span></span></span>
<span class="formula-op">) = </span>
<span class="formula-op">1/√3 × (1 - (</span>
<span class="formula-var" data-term="b3">b₃<span class="var-tooltip"><span class="var-name">b₃ = 24</span><span class="var-description">Third Betti number of G2 manifold</span></span></span>
<span class="formula-op"> - </span>
<span class="formula-var" data-term="b2">b₂<span class="var-tooltip"><span class="var-name">b₂ = 4</span><span class="var-description">Second Betti number (Kahler moduli)</span></span></span>
<span class="formula-op">×</span>
<span class="formula-var" data-term="ngen">n_gen<span class="var-tooltip"><span class="var-name">n_gen = 3</span><span class="var-description">Number of fermion generations</span></span></span>
<span class="formula-op">)/(2×</span>
<span class="formula-var" data-term="chi">χ_eff<span class="var-tooltip"><span class="var-name">χ_eff = 144</span><span class="var-description">Effective Euler characteristic</span></span></span>
<span class="formula-op">))</span>'''
print('Added: pmns-theta-12')

# 5. hubble-tension-resolution
formulas['hubble-tension-resolution']['terms'] = {
    'H0_geo': {'description': 'Geometric Hubble constant from G2 topology', 'symbol': 'H₀_geo'},
    '70.42': {'description': 'Predicted value in km/s/Mpc', 'value': '70.42 km/s/Mpc'}
}
formulas['hubble-tension-resolution']['html'] = '''<span class="formula-var" data-term="H0">H₀<sup>geo</sup><span class="var-tooltip"><span class="var-name">H₀_geo</span><span class="var-description">Geometric Hubble constant derived from G2 topology</span></span></span>
<span class="formula-op"> = </span>
<span class="formula-var" data-term="value">70.42<span class="var-tooltip"><span class="var-name">70.42 km/s/Mpc</span><span class="var-description">Resolves tension between early (67.4) and late (73.0) universe measurements</span></span></span>
<span class="formula-op"> km/s/Mpc</span>'''
print('Added: hubble-tension-resolution')

# 6. modular-anomaly-condition
formulas['modular-anomaly-condition']['terms'] = {
    'b3': {'description': 'Third Betti number', 'symbol': 'b₃'},
    '24': {'description': 'Modular divisor from string theory consistency', 'symbol': '24'}
}
formulas['modular-anomaly-condition']['html'] = '''<span class="formula-var" data-term="b3">b₃<span class="var-tooltip"><span class="var-name">b₃</span><span class="var-description">Third Betti number of G2 manifold</span></span></span>
<span class="formula-op"> ≡ 0 (mod </span>
<span class="formula-var" data-term="24">24<span class="var-tooltip"><span class="var-name">24</span><span class="var-description">Modular divisor from string theory anomaly cancellation</span></span></span>
<span class="formula-op">)</span>'''
print('Added: modular-anomaly-condition')

# 7. calabi-yau-projection
formulas['calabi-yau-projection']['terms'] = {
    'V7': {'description': '7-dimensional G2 manifold', 'symbol': 'V₇'},
    'M4': {'description': '4D Minkowski spacetime', 'symbol': 'M⁴'},
    'K6': {'description': '6D Calabi-Yau factor', 'symbol': 'K⁶'},
    'CY3': {'description': 'Calabi-Yau 3-fold projection', 'symbol': 'CY₃'}
}
formulas['calabi-yau-projection']['html'] = '''<span class="formula-var" data-term="V7">V₇<span class="var-tooltip"><span class="var-name">V₇</span><span class="var-description">7-dimensional G2 holonomy manifold</span></span></span>
<span class="formula-op"> →<sup>CY₃</sup> </span>
<span class="formula-var" data-term="M4">M⁴<span class="var-tooltip"><span class="var-name">M⁴</span><span class="var-description">4-dimensional Minkowski spacetime (observable universe)</span></span></span>
<span class="formula-op"> × </span>
<span class="formula-var" data-term="K6">K⁶<span class="var-tooltip"><span class="var-name">K⁶</span><span class="var-description">6-dimensional compactified Calabi-Yau factor</span></span></span>'''
print('Added: calabi-yau-projection')

# 8. v21-euclidean-bridge (REPLACES deprecated spr2-gauge)
# v21+ uses 12x(2,0) Euclidean bridge pairs instead of Sp(2,R) gauge fixing
formulas['spr2-gauge']['terms'] = {
    'bridge': {'description': '12 Euclidean bridge pairs', 'symbol': '12×(2,0)'},
    'Lambda': {'description': 'Cosmological constant', 'symbol': 'Λ'},
    'shadow': {'description': 'Dual-shadow structure', 'symbol': 'N+M'}
}
formulas['spr2-gauge']['html'] = '''<span class="formula-var" data-term="bridge">12×(2,0)<span class="var-tooltip"><span class="var-name">12×(2,0)</span><span class="var-description">Euclidean bridge pairs in (24,1) signature (v21+)</span></span></span>
<span class="formula-op"> → </span>
<span class="formula-var" data-term="shadow">Normal + Mirror<span class="var-tooltip"><span class="var-name">N+M</span><span class="var-description">Dual-shadow structure via OR reduction R_perp</span></span></span>'''
print('Added: v21-euclidean-bridge (replaces spr2-gauge)')

data['formulas'] = formulas

with open('h:/Github/PrincipiaMetaphysica/AutoGenerated/formulas.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print('\nDone!')

# Verify
with_html = sum(1 for f in formulas.values() if 'html' in f)
with_terms = sum(1 for f in formulas.values() if f.get('terms'))
print(f'Now {with_html}/320 with HTML, {with_terms}/320 with terms')
