"""
Generate Publication-Quality Figures for Principia Metaphysica v24.1 Submission
================================================================================

Creates 4 publication-ready figures for journal submission:
1. M27 Bulk Decomposition Diagram
2. Global Convergence Scatter Plot
3. ALP Discovery Window (IAXO Sensitivity)
4. p-value Distribution (EDOF=3 Validation)

Copyright (c) 2025-2026 Andrew Keith Watts. All rights reserved.
"""

from pathlib import Path
import json
import numpy as np
from scipy.stats import chi2

# Workaround for matplotlib packaging import issue on Windows
try:
    import packaging.version
except ImportError:
    pass

# Import matplotlib with explicit backend
import matplotlib
matplotlib.use('Agg')  # Non-interactive backend
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.patches import FancyBboxPatch, Rectangle, Ellipse, FancyArrowPatch
from matplotlib.lines import Line2D

# Repo root
REPO_ROOT = Path(__file__).parent.parent

# Paths
PLOTS_DIR = REPO_ROOT / "AutoGenerated" / "plots"
PARAMS_FILE = REPO_ROOT / "AutoGenerated" / "parameters.json"
STATS_FILE = REPO_ROOT / "AutoGenerated" / "statistical_rigor_report.json"

# Publication quality settings
plt.rcParams.update({
    'font.size': 12,
    'axes.labelsize': 14,
    'axes.titlesize': 16,
    'xtick.labelsize': 11,
    'ytick.labelsize': 11,
    'legend.fontsize': 11,
    'figure.titlesize': 18,
    'font.family': 'serif',
    'font.serif': ['Times New Roman', 'DejaVu Serif'],
    'mathtext.fontset': 'dejavuserif',
    'axes.grid': True,
    'grid.alpha': 0.3,
    'grid.linestyle': '--',
    'lines.linewidth': 2,
    'axes.linewidth': 1.2,
})

# Ensure plots directory exists
PLOTS_DIR.mkdir(parents=True, exist_ok=True)

def load_data():
    """Load parameters and statistics data."""
    with open(PARAMS_FILE, 'r', encoding='utf-8') as f:
        params_data = json.load(f)
    with open(STATS_FILE, 'r', encoding='utf-8') as f:
        stats_data = json.load(f)
    return params_data, stats_data


# =============================================================================
# FIGURE 1: M27 BULK DECOMPOSITION DIAGRAM
# =============================================================================

def generate_figure1_m27_decomposition():
    """
    Figure 1: M^27(24,1,2) Bulk Decomposition Diagram
    Shows: M^27(24,1,2) = (24+1) ⊕ (0,2)
    Components: Leech Lattice Λ₂₄ (24D), Unified Time T¹ (1D), S_EIS (0,2)
    """
    print("\n[Figure 1] Generating M27 Bulk Decomposition Diagram...")

    fig, ax = plt.subplots(figsize=(14, 10))
    ax.set_xlim(0, 10)
    ax.set_ylim(0, 10)
    ax.axis('off')

    # Title
    ax.text(5, 9.5, r'$M^{27}(24,1,2)$ Bulk Decomposition',
            ha='center', fontsize=20, fontweight='bold')
    ax.text(5, 9.0, r'$M^{27}(24,1,2) = \Lambda_{24} \oplus T^1 \oplus \mathcal{S}_{\mathrm{EIS}}$',
            ha='center', fontsize=16, style='italic')

    # Main M27 box
    main_box = FancyBboxPatch((0.5, 3.5), 9, 4.8,
                              boxstyle="round,pad=0.1",
                              edgecolor='black', facecolor='lightblue',
                              linewidth=3, alpha=0.3)
    ax.add_patch(main_box)
    ax.text(5, 8.0, r'$M^{27}(24,1,2)$ - 27D Spacetime',
            ha='center', fontsize=15, fontweight='bold')

    # Leech Lattice Λ₂₄ (24D G2 core)
    leech_box = FancyBboxPatch((1.0, 5.0), 3.5, 2.5,
                               boxstyle="round,pad=0.08",
                               edgecolor='darkblue', facecolor='lightcyan',
                               linewidth=2.5, alpha=0.6)
    ax.add_patch(leech_box)
    ax.text(2.75, 7.0, r'$\Lambda_{24}$ (Leech Lattice)',
            ha='center', fontsize=13, fontweight='bold')
    ax.text(2.75, 6.5, r'24D G₂ Core', ha='center', fontsize=11)
    ax.text(2.75, 6.1, r'12 × $(2,0)$ Bridge Pairs', ha='center', fontsize=10)
    ax.text(2.75, 5.65, r'$b_3 = 24$ (Betti Number)', ha='center', fontsize=9)
    ax.text(2.75, 5.3, r'G₂ Holonomy', ha='center', fontsize=9, style='italic')

    # Unified Time T¹ (1D)
    time_box = FancyBboxPatch((5.2, 5.0), 2.0, 2.5,
                              boxstyle="round,pad=0.08",
                              edgecolor='darkred', facecolor='mistyrose',
                              linewidth=2.5, alpha=0.6)
    ax.add_patch(time_box)
    ax.text(6.2, 7.0, r'$T^1$ (Time Fiber)',
            ha='center', fontsize=13, fontweight='bold')
    ax.text(6.2, 6.5, r'1D Timelike', ha='center', fontsize=11)
    ax.text(6.2, 6.0, r'Structure $(24,1,2)$', ha='center', fontsize=10)
    ax.text(6.2, 5.5, r'Unified Clock', ha='center', fontsize=9, style='italic')

    # Central Sampler S_EIS (0,2)
    sampler_box = FancyBboxPatch((7.8, 5.0), 1.7, 2.5,
                                 boxstyle="round,pad=0.08",
                                 edgecolor='darkgreen', facecolor='honeydew',
                                 linewidth=2.5, alpha=0.6)
    ax.add_patch(sampler_box)
    ax.text(8.65, 7.0, r'$\mathcal{S}_{\mathrm{EIS}}$',
            ha='center', fontsize=13, fontweight='bold')
    ax.text(8.65, 6.5, r'Central Sampler', ha='center', fontsize=10)
    ax.text(8.65, 6.1, r'$(0,2)$ Dimensions', ha='center', fontsize=9)
    ax.text(8.65, 5.65, r'Averaging', ha='center', fontsize=9, style='italic')
    ax.text(8.65, 5.3, r'Architecture', ha='center', fontsize=9, style='italic')

    # Dimensional Descent Chain
    ax.text(5, 3.0, 'Dimensional Descent Chain:',
            ha='center', fontsize=14, fontweight='bold')

    descent_y = 2.3
    descent_text = [
        (r'$27D$', 'Full Bulk'),
        (r'$\rightarrow$', ''),
        (r'$13D$', 'Intermediate'),
        (r'$\rightarrow$', ''),
        (r'$7D$', 'G₂ Manifold'),
        (r'$\rightarrow$', ''),
        (r'$4D$', 'Spacetime')
    ]

    x_positions = np.linspace(2, 8, len(descent_text))
    for x, (dim, label) in zip(x_positions, descent_text):
        if dim == r'$\rightarrow$':
            ax.text(x, descent_y, dim, ha='center', fontsize=16, fontweight='bold')
        else:
            box = FancyBboxPatch((x-0.3, descent_y-0.15), 0.6, 0.35,
                                boxstyle="round,pad=0.03",
                                edgecolor='purple', facecolor='lavender',
                                linewidth=1.5, alpha=0.5)
            ax.add_patch(box)
            ax.text(x, descent_y+0.05, dim, ha='center', fontsize=12, fontweight='bold')
            if label:
                ax.text(x, descent_y-0.35, label, ha='center', fontsize=8, style='italic')

    # Metric formula at bottom
    metric_box = FancyBboxPatch((1.0, 0.3), 8, 0.8,
                                boxstyle="round,pad=0.05",
                                edgecolor='gray', facecolor='lightyellow',
                                linewidth=1.5, alpha=0.4)
    ax.add_patch(metric_box)
    ax.text(5, 0.85, r'Metric:', ha='center', fontsize=11, fontweight='bold')
    ax.text(5, 0.55,
            r'$ds^2 = -dt^2 + \sum_{i=1}^{12} (dy_{1i}^2 + dy_{2i}^2) + (ds_1^2 + ds_2^2)$',
            ha='center', fontsize=11, style='italic')

    # Save figure
    output_path = PLOTS_DIR / "figure1_m27_decomposition.png"
    plt.savefig(output_path, dpi=300, bbox_inches='tight', facecolor='white')
    output_path_pdf = PLOTS_DIR / "figure1_m27_decomposition.pdf"
    plt.savefig(output_path_pdf, bbox_inches='tight', facecolor='white')
    plt.close()

    print(f"  OK Saved: {output_path}")
    print(f"  OK Saved: {output_path_pdf}")


# =============================================================================
# FIGURE 2: GLOBAL CONVERGENCE SCATTER PLOT
# =============================================================================

def generate_figure2_convergence_scatter(params_data):
    """
    Figure 2: Global Convergence Scatter Plot
    X-axis: PM Predicted Values
    Y-axis: Experimental Values
    Color: PASS (green), MARGINAL (yellow), FAIL (red)
    """
    print("\n[Figure 2] Generating Global Convergence Scatter Plot...")

    # Extract testable parameters (with experimental values)
    params = params_data['parameters']

    testable = []
    for param_id, data in params.items():
        if (data.get('experimental_value') is not None and
            data.get('value') is not None and
            data.get('validation_status') in ['PASS', 'MARGINAL', 'FAIL']):

            # Skip if values are exactly identical (likely inputs)
            if data['value'] != data['experimental_value']:
                sigma_dev = data.get('sigma_deviation', 0)
                if sigma_dev is None:
                    sigma_dev = 0

                uncertainty = data.get('experimental_uncertainty', 0)
                if uncertainty is None or uncertainty == 0:
                    uncertainty = abs(data['value'] - data['experimental_value']) * 0.01  # 1% default

                testable.append({
                    'id': param_id,
                    'predicted': data['value'],
                    'experimental': data['experimental_value'],
                    'uncertainty': uncertainty,
                    'status': data.get('validation_status', 'UNKNOWN'),
                    'sigma': abs(sigma_dev)
                })

    print(f"  Found {len(testable)} testable parameters")

    if len(testable) == 0:
        print("  WARNING: No testable parameters found!")
        return

    # Prepare data arrays
    predicted = np.array([p['predicted'] for p in testable])
    experimental = np.array([p['experimental'] for p in testable])
    uncertainties = np.array([p['uncertainty'] for p in testable])
    statuses = np.array([p['status'] for p in testable])
    sigmas = np.array([p['sigma'] for p in testable])

    # Create figure
    fig, ax = plt.subplots(figsize=(12, 12))

    # Color mapping
    color_map = {'PASS': 'green', 'MARGINAL': 'orange', 'FAIL': 'red'}
    colors = [color_map.get(s, 'gray') for s in statuses]

    # Determine if log scale is needed
    use_log = (np.max(np.abs(predicted)) / np.min(np.abs(predicted[predicted != 0])) > 1000)

    if use_log:
        # Log scale scatter
        ax.set_xscale('log')
        ax.set_yscale('log')

        # Filter out zeros for log scale
        mask = (predicted > 0) & (experimental > 0)
        predicted_log = predicted[mask]
        experimental_log = experimental[mask]
        uncertainties_log = uncertainties[mask]
        colors_log = [colors[i] for i in range(len(colors)) if mask[i]]

        # Scatter plot
        ax.scatter(predicted_log, experimental_log, c=colors_log,
                  s=100, alpha=0.7, edgecolors='black', linewidth=1.5, zorder=3)

        # Error bars
        ax.errorbar(predicted_log, experimental_log, yerr=uncertainties_log,
                   fmt='none', ecolor='gray', alpha=0.4, capsize=3, zorder=2)

        # Diagonal line (perfect agreement)
        min_val = min(np.min(predicted_log), np.min(experimental_log))
        max_val = max(np.max(predicted_log), np.max(experimental_log))
        ax.plot([min_val, max_val], [min_val, max_val],
               'k--', linewidth=2, label='Perfect Agreement (y = x)', zorder=1)

    else:
        # Linear scale scatter
        ax.scatter(predicted, experimental, c=colors,
                  s=100, alpha=0.7, edgecolors='black', linewidth=1.5, zorder=3)

        # Error bars
        ax.errorbar(predicted, experimental, yerr=uncertainties,
                   fmt='none', ecolor='gray', alpha=0.4, capsize=3, zorder=2)

        # Diagonal line
        min_val = min(np.min(predicted), np.min(experimental))
        max_val = max(np.max(predicted), np.max(experimental))
        ax.plot([min_val, max_val], [min_val, max_val],
               'k--', linewidth=2, label='Perfect Agreement (y = x)', zorder=1)

    # Annotate key parameters (highest sigma deviations)
    key_params = sorted(testable, key=lambda p: p['sigma'], reverse=True)[:5]
    for param in key_params:
        if use_log and (param['predicted'] <= 0 or param['experimental'] <= 0):
            continue

        label = param['id'].split('.')[-1]  # Extract short name
        ax.annotate(label,
                   xy=(param['predicted'], param['experimental']),
                   xytext=(10, 10), textcoords='offset points',
                   fontsize=9, alpha=0.8,
                   bbox=dict(boxstyle='round,pad=0.3', facecolor='yellow', alpha=0.5),
                   arrowprops=dict(arrowstyle='->', connectionstyle='arc3,rad=0.2',
                                  color='black', lw=1))

    # Labels and title
    ax.set_xlabel('PM Predicted Values', fontsize=16, fontweight='bold')
    ax.set_ylabel('Experimental Values', fontsize=16, fontweight='bold')
    ax.set_title(f'Global Convergence: PM Predictions vs. Experiment\n({len(testable)} Testable Parameters)',
                fontsize=18, fontweight='bold', pad=20)

    # Legend
    legend_elements = [
        Line2D([0], [0], marker='o', color='w', label='PASS (≤2σ)',
              markerfacecolor='green', markersize=10, markeredgecolor='black'),
        Line2D([0], [0], marker='o', color='w', label='MARGINAL (2-3σ)',
              markerfacecolor='orange', markersize=10, markeredgecolor='black'),
        Line2D([0], [0], marker='o', color='w', label='FAIL (>3σ)',
              markerfacecolor='red', markersize=10, markeredgecolor='black'),
        Line2D([0], [0], color='black', linestyle='--', linewidth=2, label='Perfect Agreement')
    ]
    ax.legend(handles=legend_elements, loc='upper left', fontsize=12, framealpha=0.9)

    # Grid
    ax.grid(True, alpha=0.3, linestyle='--', linewidth=0.8)

    # Statistics text box
    pass_count = np.sum(statuses == 'PASS')
    marginal_count = np.sum(statuses == 'MARGINAL')
    fail_count = np.sum(statuses == 'FAIL')

    stats_text = (f"Statistics:\n"
                 f"PASS: {pass_count} ({100*pass_count/len(testable):.1f}%)\n"
                 f"MARGINAL: {marginal_count} ({100*marginal_count/len(testable):.1f}%)\n"
                 f"FAIL: {fail_count} ({100*fail_count/len(testable):.1f}%)")

    ax.text(0.98, 0.02, stats_text,
           transform=ax.transAxes, fontsize=11,
           verticalalignment='bottom', horizontalalignment='right',
           bbox=dict(boxstyle='round', facecolor='white', alpha=0.8, edgecolor='black'))

    # Save figure
    output_path = PLOTS_DIR / "figure2_convergence_scatter.png"
    plt.savefig(output_path, dpi=300, bbox_inches='tight', facecolor='white')
    output_path_pdf = PLOTS_DIR / "figure2_convergence_scatter.pdf"
    plt.savefig(output_path_pdf, bbox_inches='tight', facecolor='white')
    plt.close()

    print(f"  OK Saved: {output_path}")
    print(f"  OK Saved: {output_path_pdf}")


# =============================================================================
# FIGURE 3: ALP DISCOVERY WINDOW (IAXO SENSITIVITY)
# =============================================================================

def generate_figure3_alp_discovery_window():
    """
    Figure 3: ALP Discovery Window (IAXO Sensitivity)
    X-axis: ALP mass m_a (meV) - log scale
    Y-axis: Photon coupling g_aγγ (GeV⁻¹) - log scale
    PM Prediction: Red star at (3.51 meV, 10⁻¹¹ GeV⁻¹)
    """
    print("\n[Figure 3] Generating ALP Discovery Window...")

    fig, ax = plt.subplots(figsize=(12, 10))

    # Mass range (meV)
    m_a = np.logspace(-1, 1, 200)  # 0.1 to 10 meV

    # CAST exclusion limit (approximate)
    # CAST: g_aγγ < 0.66 × 10⁻¹⁰ GeV⁻¹ for m_a < 0.02 eV = 20 meV
    cast_limit = np.full_like(m_a, 0.66e-10)
    cast_limit[m_a > 20] = np.nan  # CAST only excludes up to ~20 meV

    # IAXO projected sensitivity (2025-2028)
    # IAXO: g_aγγ ~ 10⁻¹¹ GeV⁻¹ for m_a ~ 0.01-10 meV
    iaxo_sensitivity = np.full_like(m_a, 1.5e-11)
    iaxo_sensitivity[m_a < 0.5] = 1.5e-11 * (0.5 / m_a[m_a < 0.5])**0.3  # Slightly worse at low mass
    iaxo_sensitivity[m_a > 10] = np.nan

    # BabyIAXO sensitivity (intermediate step)
    babyiaxo_sensitivity = np.full_like(m_a, 1.5e-10)
    babyiaxo_sensitivity[m_a > 15] = np.nan

    # PM Prediction: m_a = 3.51 meV, g_aγγ = 10⁻¹¹ GeV⁻¹
    pm_mass = 3.51  # meV
    pm_coupling = 1.0e-11  # GeV⁻¹
    pm_mass_error = 0.5  # meV (uncertainty)
    pm_coupling_error = 0.3e-11  # GeV⁻¹ (uncertainty)

    # Plot exclusion regions
    ax.fill_between(m_a, cast_limit, 1e-8, where=~np.isnan(cast_limit),
                    alpha=0.4, color='red', label='CAST Excluded (2017)')
    ax.plot(m_a, cast_limit, 'r-', linewidth=2)

    # Plot future sensitivities
    ax.plot(m_a, babyiaxo_sensitivity, 'b--', linewidth=2.5, label='BabyIAXO Projected (2024-2025)')
    ax.plot(m_a, iaxo_sensitivity, 'purple', linewidth=3, label='IAXO Projected (2025-2028)')
    ax.fill_between(m_a, iaxo_sensitivity, 1e-13, where=~np.isnan(iaxo_sensitivity),
                    alpha=0.2, color='purple')

    # PM Prediction with error box
    ax.errorbar(pm_mass, pm_coupling,
               xerr=pm_mass_error, yerr=pm_coupling_error,
               fmt='*', color='red', markersize=25,
               markeredgecolor='darkred', markeredgewidth=2,
               ecolor='darkred', elinewidth=3, capsize=8, capthick=3,
               label='PM Prediction', zorder=10)

    # Discovery window annotation
    ax.annotate('Detection Window\n2025-2028',
               xy=(pm_mass, pm_coupling), xytext=(1.2, 5e-11),
               fontsize=13, fontweight='bold', color='purple',
               bbox=dict(boxstyle='round,pad=0.5', facecolor='yellow', alpha=0.7, edgecolor='purple', linewidth=2),
               arrowprops=dict(arrowstyle='->', lw=3, color='purple', connectionstyle='arc3,rad=0.3'))

    # Principia Metric label
    ax.text(pm_mass, pm_coupling * 0.3, 'Principia Metric\nPrediction',
           ha='center', fontsize=11, fontweight='bold', color='darkred',
           bbox=dict(boxstyle='round,pad=0.4', facecolor='white', alpha=0.8, edgecolor='red', linewidth=1.5))

    # Axes and labels
    ax.set_xscale('log')
    ax.set_yscale('log')
    ax.set_xlabel(r'ALP Mass $m_a$ (meV)', fontsize=16, fontweight='bold')
    ax.set_ylabel(r'Photon Coupling $g_{a\gamma\gamma}$ (GeV$^{-1}$)', fontsize=16, fontweight='bold')
    ax.set_title('ALP Discovery Window: IAXO Sensitivity vs. PM Prediction\n'
                r'Axion-Like Particle Detection Prospects (2025-2028)',
                fontsize=18, fontweight='bold', pad=20)

    ax.set_xlim(0.1, 10)
    ax.set_ylim(1e-12, 1e-8)

    # Legend
    ax.legend(loc='upper right', fontsize=12, framealpha=0.9, edgecolor='black', fancybox=True)

    # Grid
    ax.grid(True, which='both', alpha=0.3, linestyle='--', linewidth=0.8)

    # Save figure
    output_path = PLOTS_DIR / "figure3_alp_discovery_window.png"
    plt.savefig(output_path, dpi=300, bbox_inches='tight', facecolor='white')
    output_path_pdf = PLOTS_DIR / "figure3_alp_discovery_window.pdf"
    plt.savefig(output_path_pdf, bbox_inches='tight', facecolor='white')
    plt.close()

    print(f"  OK Saved: {output_path}")
    print(f"  OK Saved: {output_path_pdf}")


# =============================================================================
# FIGURE 4: P-VALUE DISTRIBUTION (EDOF=3 VALIDATION)
# =============================================================================

def generate_figure4_pvalue_distribution(stats_data):
    """
    Figure 4: p-value Distribution (EDOF=3 Validation)
    Shows chi-squared distribution for EDOF = 3
    Marks observed χ² = 5.751 with vertical line
    Shades "Trust Zone" (p = 0.05 to 0.95) in green
    """
    print("\n[Figure 4] Generating p-value Distribution (EDOF=3)...")

    # Extract EDOF analysis data
    edof_data = stats_data['edof_analysis']
    chi_sq_obs = edof_data['chi_squared']
    edof = edof_data['effective_dof']
    traditional_dof = edof_data['traditional_dof']
    p_value_obs = edof_data['p_value']

    print(f"  chi^2 = {chi_sq_obs:.3f}, EDOF = {edof}, p-value = {p_value_obs:.4f}")

    # Create figure
    fig, ax = plt.subplots(figsize=(14, 10))

    # Chi-squared distributions
    chi_sq_range = np.linspace(0, 20, 1000)

    # EDOF = 3 distribution
    pdf_edof3 = chi2.pdf(chi_sq_range, edof)

    # Traditional DOF = 25 distribution (for comparison)
    pdf_dof25 = chi2.pdf(chi_sq_range, traditional_dof)

    # Plot distributions
    ax.plot(chi_sq_range, pdf_edof3, 'b-', linewidth=3, label=f'χ² Distribution (EDOF = {edof})')
    ax.plot(chi_sq_range, pdf_dof25, 'gray', linestyle='--', linewidth=2.5,
           label=f'χ² Distribution (Traditional DOF = {traditional_dof})', alpha=0.6)

    # Shade regions
    # Trust Zone: p = 0.05 to 0.95 (credible fit)
    chi_sq_lower = chi2.ppf(0.05, edof)  # 5% lower tail
    chi_sq_upper = chi2.ppf(0.95, edof)  # 95% upper tail

    trust_zone_mask = (chi_sq_range >= chi_sq_lower) & (chi_sq_range <= chi_sq_upper)
    ax.fill_between(chi_sq_range, 0, pdf_edof3, where=trust_zone_mask,
                   alpha=0.3, color='green', label='Trust Zone (p ∈ [0.05, 0.95])')

    # Too Good Zone: p > 0.95 (suspiciously perfect)
    too_good_mask = chi_sq_range < chi_sq_lower
    ax.fill_between(chi_sq_range, 0, pdf_edof3, where=too_good_mask,
                   alpha=0.3, color='red', label='Too Good (p > 0.95)')

    # Poor Fit Zone: p < 0.05 (bad fit)
    poor_fit_mask = chi_sq_range > chi_sq_upper
    ax.fill_between(chi_sq_range, 0, pdf_edof3, where=poor_fit_mask,
                   alpha=0.3, color='orange', label='Poor Fit (p < 0.05)')

    # Observed χ² line
    ax.axvline(chi_sq_obs, color='darkblue', linestyle='-', linewidth=4,
              label=f'PM Observed: χ² = {chi_sq_obs:.3f}', zorder=10)

    # Annotation for PM result
    ax.annotate(f'PM Result:\nχ² = {chi_sq_obs:.3f}\np = {p_value_obs:.3f}\n(CREDIBLE)',
               xy=(chi_sq_obs, chi2.pdf(chi_sq_obs, edof)),
               xytext=(chi_sq_obs + 3, chi2.pdf(chi_sq_obs, edof) + 0.05),
               fontsize=13, fontweight='bold', color='darkblue',
               bbox=dict(boxstyle='round,pad=0.6', facecolor='lightyellow',
                        alpha=0.9, edgecolor='darkblue', linewidth=2.5),
               arrowprops=dict(arrowstyle='->', lw=3, color='darkblue', connectionstyle='arc3,rad=0.3'))

    # Expected value line (mean of χ² distribution = DOF)
    ax.axvline(edof, color='green', linestyle=':', linewidth=2.5, alpha=0.7,
              label=f'Expected Value: χ² = {edof}')

    # Labels and title
    ax.set_xlabel(r'χ² Value', fontsize=16, fontweight='bold')
    ax.set_ylabel(r'Probability Density', fontsize=16, fontweight='bold')
    ax.set_title(r'Statistical Validation: χ² Distribution with EDOF = 3' + '\n' +
                'Principia Metaphysica v24.1 Fit Quality Assessment',
                fontsize=18, fontweight='bold', pad=20)

    # Legend
    ax.legend(loc='upper right', fontsize=11, framealpha=0.95, edgecolor='black',
             fancybox=True, shadow=True)

    # Grid
    ax.grid(True, alpha=0.3, linestyle='--', linewidth=0.8)

    # Set limits
    ax.set_xlim(0, 18)
    ax.set_ylim(0, None)

    # Comparison text box
    comparison_text = (
        "EDOF vs. Traditional DOF:\n"
        f"• EDOF = {edof}: Reduced χ² = {edof_data['reduced_chi_squared']:.3f}\n"
        f"• Traditional DOF = {traditional_dof}: Reduced χ² = {edof_data['comparison']['traditional_approach']['reduced_chi_sq']:.3f}\n"
        "\n"
        f"EDOF properly accounts for topological\n"
        f"correlation structure (3 independent seeds).\n"
        f"Traditional DOF assumes independence,\n"
        f"which violates PM's unified topology."
    )

    ax.text(0.02, 0.98, comparison_text,
           transform=ax.transAxes, fontsize=10,
           verticalalignment='top', horizontalalignment='left',
           bbox=dict(boxstyle='round,pad=0.6', facecolor='white', alpha=0.9,
                    edgecolor='black', linewidth=1.5))

    # Save figure
    output_path = PLOTS_DIR / "figure4_pvalue_distribution.png"
    plt.savefig(output_path, dpi=300, bbox_inches='tight', facecolor='white')
    output_path_pdf = PLOTS_DIR / "figure4_pvalue_distribution.pdf"
    plt.savefig(output_path_pdf, bbox_inches='tight', facecolor='white')
    plt.close()

    print(f"  OK Saved: {output_path}")
    print(f"  OK Saved: {output_path_pdf}")


# =============================================================================
# MAIN EXECUTION
# =============================================================================

def main():
    """Generate all 4 publication-quality figures."""
    print("\n" + "="*70)
    print("  PRINCIPIA METAPHYSICA v24.1 - PUBLICATION FIGURE GENERATION")
    print("="*70)

    # Load data
    print("\nLoading data...")
    params_data, stats_data = load_data()
    print(f"  OK Loaded {len(params_data['parameters'])} parameters")
    print(f"  OK Loaded statistical rigor report")

    # Generate figures
    generate_figure1_m27_decomposition()
    generate_figure2_convergence_scatter(params_data)
    generate_figure3_alp_discovery_window()
    generate_figure4_pvalue_distribution(stats_data)

    print("\n" + "="*70)
    print("  ALL FIGURES GENERATED SUCCESSFULLY!")
    print("="*70)
    print(f"\nOutput directory: {PLOTS_DIR}")
    print("\nGenerated files:")
    print("  1. figure1_m27_decomposition.png/.pdf")
    print("  2. figure2_convergence_scatter.png/.pdf")
    print("  3. figure3_alp_discovery_window.png/.pdf")
    print("  4. figure4_pvalue_distribution.png/.pdf")
    print("\nReady for journal submission!")
    print("="*70 + "\n")


if __name__ == "__main__":
    main()
