#!/usr/bin/env python3
"""
PM Config v16.1 - High-Precision Simulation Configuration
==========================================================

Central configuration for numerical precision, Monte Carlo sampling,
and physics anchors. Toggle HIGH_RIGOR_MODE for publication vs development.

Copyright (c) 2025-2026 Andrew Keith Watts. All rights reserved.
"""

import numpy as np


class PMConfig:
    """
    Master configuration for v16.1 simulations.
    Set HIGH_RIGOR_MODE = True for publication-grade results.
    """

    # =========================================================================
    # THE MASTER SWITCH
    # =========================================================================
    HIGH_RIGOR_MODE: bool = True

    # =========================================================================
    # NUMERICAL ENGINE SETTINGS
    # =========================================================================

    # Absolute tolerance for ODE solvers
    ABS_TOL: float = 1e-12 if HIGH_RIGOR_MODE else 1e-6

    # Relative tolerance for ODE solvers
    REL_TOL: float = 1e-10 if HIGH_RIGOR_MODE else 1e-4

    # Integration method: RK45 (adaptive) vs RK23 (fast)
    ODE_METHOD: str = 'RK45' if HIGH_RIGOR_MODE else 'RK23'

    # Number of RK steps for fixed-step methods
    RK_STEPS: int = 1000 if HIGH_RIGOR_MODE else 100

    # =========================================================================
    # MONTE CARLO SETTINGS
    # =========================================================================

    # Number of MC samples for Yukawa integrals
    # 10^7 gives ~0.03% error, 10^4 gives ~1% error
    MC_SAMPLES: int = 10**7 if HIGH_RIGOR_MODE else 10**4

    # Random seed for reproducibility (None for random)
    MC_SEED: int = 42 if HIGH_RIGOR_MODE else None

    # =========================================================================
    # PHYSICS ANCHORS (from G₂ topology)
    # =========================================================================

    # Critical redshift for G₂ modulus stabilization (EDE transition)
    Z_CRITICAL: float = 3540.0

    # Early universe Hubble constant (Planck 2018/2025)
    H0_EARLY: float = 67.4  # km/s/Mpc

    # Local Hubble constant target (SH0ES 2025)
    H0_LOCAL: float = 73.04  # km/s/Mpc

    # G₂ stabilization time (Planck seconds)
    G2_STABILIZATION_TIME: float = 1e-32

    # G₂ radius limit for compactification
    G2_RADIUS_LIMIT: float = 7.102

    # =========================================================================
    # TORSION VALIDATION
    # =========================================================================

    # Maximum allowed torsion norm for G₂ holonomy
    TORSION_TOLERANCE: float = 1e-15

    # Enable automatic torsion surgery if exceeded
    AUTO_TORSION_SURGERY: bool = True

    # =========================================================================
    # COSMOLOGY PARAMETERS (DESI 2025)
    # =========================================================================

    # Matter density
    OMEGA_M: float = 0.311

    # Dark energy density
    OMEGA_DE: float = 0.689

    # w₀ target (DESI 2025 dynamical DE)
    W0_TARGET: float = -0.727

    # wₐ target (DESI 2025)
    WA_TARGET: float = -1.05

    # =========================================================================
    # NEUTRINO PARAMETERS (NuFIT 6.0 2025)
    # =========================================================================

    # Mass ordering preference (True = Normal, False = Inverted)
    NORMAL_ORDERING: bool = True

    # δ_CP best fit for NO
    DELTA_CP_NO: float = 232.0  # degrees

    # δ_CP best fit for IO
    DELTA_CP_IO: float = 270.0  # degrees

    # =========================================================================
    # OUTPUT SETTINGS
    # =========================================================================

    # Enable verbose output during simulations
    VERBOSE: bool = True

    # Save intermediate results
    SAVE_INTERMEDIATES: bool = HIGH_RIGOR_MODE

    # Output directory
    OUTPUT_DIR: str = "AutoGenerated"

    @classmethod
    def get_config_summary(cls) -> dict:
        """Return configuration summary for logging."""
        return {
            "mode": "HIGH_RIGOR" if cls.HIGH_RIGOR_MODE else "FAST",
            "abs_tol": cls.ABS_TOL,
            "rel_tol": cls.REL_TOL,
            "ode_method": cls.ODE_METHOD,
            "mc_samples": cls.MC_SAMPLES,
            "z_critical": cls.Z_CRITICAL,
            "torsion_tolerance": cls.TORSION_TOLERANCE,
        }


if __name__ == "__main__":
    print("=" * 60)
    print("PM CONFIG v16.1")
    print("=" * 60)
    for key, value in PMConfig.get_config_summary().items():
        print(f"  {key}: {value}")
