#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Verify that the HTML content was successfully migrated to theory_output.json"""

import json
import sys
import io

# Set UTF-8 encoding for stdout
if sys.stdout.encoding != 'utf-8':
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

def main():
    with open(r'h:\Github\PrincipiaMetaphysica\AutoGenerated\theory_output.json', 'r', encoding='utf-8') as f:
        data = json.load(f)

    sections = data.get('sections', {})

    print('Migration Verification')
    print('=' * 60)
    print('\nNew sections added:')
    print(f"  - appendix_e_delta_lat: {'YES' if 'appendix_e_delta_lat' in sections else 'NO'}")
    print(f"  - appendix_f_subleading: {'YES' if 'appendix_f_subleading' in sections else 'NO'}")
    print(f"  - section_7_cmb_bubbles: {'YES' if 'section_7_cmb_bubbles' in sections else 'NO'}")

    print('\nSection details:')
    if 'appendix_e_delta_lat' in sections:
        sec = sections['appendix_e_delta_lat']
        print(f"  Appendix E: {sec.get('title')}")
        print(f"    ID: {sec.get('id')}")
        print(f"    Type: {sec.get('type')}")
        print(f"    Status: {sec.get('status')}")
        print(f"    Subsections: {len(sec.get('subsections', []))}")

    if 'appendix_f_subleading' in sections:
        sec = sections['appendix_f_subleading']
        print(f"\n  Appendix F: {sec.get('title')}")
        print(f"    ID: {sec.get('id')}")
        print(f"    Type: {sec.get('type')}")
        print(f"    Status: {sec.get('status')}")
        print(f"    Subsections: {len(sec.get('subsections', []))}")

    if 'section_7_cmb_bubbles' in sections:
        sec = sections['section_7_cmb_bubbles']
        print(f"\n  Section 7 CMB: {sec.get('title')}")
        print(f"    ID: {sec.get('id')}")
        print(f"    Type: {sec.get('type')}")
        print(f"    Subsections: {len(sec.get('subsections', []))}")

    print('\n' + '=' * 60)
    print('Migration verification complete!')

if __name__ == '__main__':
    main()
