#!/usr/bin/env python3
"""
Principia Metaphysica Package Verification Script
=================================================

Run this script to verify the integrity and functionality of the package.

Usage:
    python verify_package.py [--full]

Options:
    --full    Run full simulation tests (takes longer)
"""

import os
import sys
import json
import hashlib
from pathlib import Path

def main():
    print("=" * 60)
    print(" Principia Metaphysica Package Verification")
    print("=" * 60)

    package_dir = Path(__file__).parent
    errors = []
    warnings = []

    # 1. Check manifest exists
    print("\n[1/5] Checking manifest...")
    manifest_path = package_dir / "MANIFEST.json"
    if not manifest_path.exists():
        errors.append("MANIFEST.json not found")
    else:
        with open(manifest_path) as f:
            manifest = json.load(f)
        print(f"      Version: {manifest['version']}")
        print(f"      Files: {manifest['summary']['total_files']}")

    # 2. Check critical files exist
    print("\n[2/5] Checking critical files...")
    critical_files = [
        "config.py",
        "README.md",
        "LICENSE",
        "AutoGenerated/formulas.json",
        "AutoGenerated/parameters.json",
        "simulations/base/__init__.py",
    ]
    for cf in critical_files:
        if not (package_dir / cf).exists():
            errors.append(f"Missing: {cf}")
        else:
            print(f"      OK: {cf}")

    # 3. Check Python imports
    print("\n[3/5] Checking Python imports...")
    sys.path.insert(0, str(package_dir))
    try:
        import config
        print("      OK: config.py imports")
    except Exception as e:
        errors.append(f"config.py import failed: {e}")

    try:
        from simulations.base import PMRegistry
        print("      OK: simulations.base imports")
    except Exception as e:
        errors.append(f"simulations.base import failed: {e}")

    # 4. Check JSON data files
    print("\n[4/5] Checking JSON data files...")
    json_files = [
        "AutoGenerated/formulas.json",
        "AutoGenerated/parameters.json",
        "AutoGenerated/simulations.json",
    ]
    for jf in json_files:
        jf_path = package_dir / jf
        if jf_path.exists():
            try:
                with open(jf_path, encoding='utf-8') as f:
                    data = json.load(f)
                print(f"      OK: {jf} ({len(data) if isinstance(data, list) else 'valid'} entries)")
            except json.JSONDecodeError as e:
                errors.append(f"Invalid JSON in {jf}: {e}")
            except UnicodeDecodeError as e:
                warnings.append(f"Encoding issue in {jf}: {e}")

    # 5. Quick simulation test
    print("\n[5/5] Quick simulation test...")
    try:
        from simulations.base import PMRegistry
        from simulations.base.established import EstablishedPhysics

        registry = PMRegistry()
        EstablishedPhysics.load_into_registry(registry)

        alpha = registry.get_param("constants.alpha_em")
        print(f"      OK: alpha_em = {alpha:.6e}")
    except Exception as e:
        warnings.append(f"Simulation test warning: {e}")

    # Summary
    print("\n" + "=" * 60)
    if errors:
        print(f" FAILED - {len(errors)} error(s)")
        for e in errors:
            print(f"   ERROR: {e}")
        sys.exit(1)
    elif warnings:
        print(f" PASSED with {len(warnings)} warning(s)")
        for w in warnings:
            print(f"   WARN: {w}")
    else:
        print(" PASSED - All checks successful")
    print("=" * 60)

if __name__ == "__main__":
    main()
