"""
Intellectual Property Protection Module

This module provides tools for:
1. Cryptographic hashing of theoretical predictions
2. Timestamping discoveries with git commits
3. Creating verifiable priority claims
4. Generating IP-protected discovery registries

Main Components:
- discovery_hash_registry.py: Registry generator
- AutoGenerated/discovery_hashes.json: Output registry (generated)

Usage:
    python simulations/ip/discovery_hash_registry.py

This will create AutoGenerated/discovery_hashes.json with all key predictions.
"""

from pathlib import Path

__version__ = "1.0.0"
__author__ = "Principia Metaphysica Research Team"
__license__ = "MIT"

# Module paths
MODULE_DIR = Path(__file__).parent
REPO_ROOT = MODULE_DIR.parent.parent
OUTPUT_DIR = REPO_ROOT / "AutoGenerated"

__all__ = [
    "DiscoveryHashRegistry",
]
