#!/usr/bin/env python3
"""
Verification script for discovery hash registry.

This script verifies that all hashes in the discovery registry are correct
and have not been tampered with.
"""

import json
import hashlib
import sys
from pathlib import Path


def verify_registry(registry_path: Path) -> bool:
    """
    Verify all hashes in the registry.

    Args:
        registry_path: Path to discovery_hashes.json

    Returns:
        True if all hashes verify, False otherwise
    """
    # Load registry
    with open(registry_path, 'r', encoding='utf-8') as f:
        registry = json.load(f)

    print("Discovery Hash Registry Verification")
    print("=" * 80)
    print(f"Registry: {registry_path}")
    print(f"Version: {registry['metadata']['version']}")
    print(f"Created: {registry['metadata']['created']}")
    print(f"Git Commit: {registry['git_snapshot']['short_hash']}")
    print(f"Total Predictions: {len(registry['discoveries'])}")
    print("\n" + "=" * 80)
    print("Verifying Hashes...")
    print("=" * 80 + "\n")

    all_valid = True
    for i, entry in enumerate(registry['discoveries'], 1):
        prediction = entry['prediction']
        stored_hash = entry['discovery_hash']

        # Compute hash
        canonical = json.dumps(prediction, sort_keys=True, separators=(',', ':'))
        computed_hash = hashlib.sha256(canonical.encode('utf-8')).hexdigest()

        # Verify
        match = computed_hash == stored_hash
        all_valid = all_valid and match

        status = "[OK]" if match else "[FAIL]"
        # Use ASCII-safe output
        name = prediction['name'].encode('ascii', 'replace').decode('ascii')
        print(f"{i}. {status} {name}")
        print(f"   Stored:   {stored_hash[:32]}...")
        print(f"   Computed: {computed_hash[:32]}...")

        if not match:
            print("   ERROR: Hash mismatch detected!")
        print()

    print("=" * 80)
    if all_valid:
        print("[OK] All hashes verified successfully!")
        print("Registry integrity: VERIFIED")
    else:
        print("[FAIL] Hash verification failed!")
        print("Registry integrity: COMPROMISED")
    print("=" * 80)

    return all_valid


def main():
    """Main entry point."""
    repo_root = Path(__file__).parent.parent.parent
    registry_path = repo_root / "AutoGenerated" / "discovery_hashes.json"

    if not registry_path.exists():
        print(f"Error: Registry not found at {registry_path}")
        print("Run: python simulations/ip/discovery_hash_registry.py")
        sys.exit(1)

    # Verify registry
    success = verify_registry(registry_path)

    # Exit with appropriate code
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
